import type { ModuleInfo } from '@/types'

export const MODULES: ModuleInfo[] = [
  {
    slug: 'partenaire1', n: 1,
    titre: 'Partenaire 1',
    sousTitre: 'Connaissance de soi',
    description: 'Avant de former un couple, on commence par soi.',
    emoji: '🪞', free: true, annuel: false,
    introTexte: '',
    outroTexte: '',
    questions: [
      { slug: 'comment_vous_decririez_vous_soyez_libre', type: 'text', texte: 'Comment vous décririez-vous ? (soyez libre de décrire physiquement, parcours de vie, caractère, ...)', texteInitiateur: 'Comment vous décririez-vous ? (soyez libre de décrire physiquement, parcours de vie, caractère, ...)', textePartenaire: 'Comment décririez-vous l\'autre ? (soyez libre de décrire physiquement, parcours de vie, caractère, ...)' },
      { slug: 'quelles_sont_vos_grandes_qualites', type: 'text', texte: 'Quelles sont vos grandes qualités ?', texteInitiateur: 'Quelles sont vos grandes qualités ?', textePartenaire: 'Quelles sont ses grandes qualités ?' },
      { slug: 'quelle_est_votre_plus_grande_blessure_ab', type: 'text', texte: 'Quelle est votre plus grande blessure (abandon, trahison, rejet, humiliation, injustice, autre) ?', texteInitiateur: 'Quelle est votre plus grande blessure (abandon, trahison, rejet, humiliation, injustice, autre) ?', textePartenaire: 'Quelle est sa plus grande blessure (abandon, trahison, rejet, humiliation, injustice, autre) ?' },
      { slug: 'qu_est_ce_qui_vous_passionne', type: 'text', texte: 'Qu\'est-ce qui vous passionne ?', texteInitiateur: 'Qu\'est-ce qui vous passionne ?', textePartenaire: 'Qu\'est-ce qui le ou la passionne ?' },
      { slug: 'avez_vous_un_but_dans_la_vie', type: 'text', texte: 'Avez-vous un but dans la vie ?', texteInitiateur: 'Avez-vous un but dans la vie ?', textePartenaire: 'A t-elle/il un but dans la vie ?' },
      { slug: 'pour_vous_qu_est_ce_que_le_bonheur', type: 'text', texte: 'Pour vous, qu\'est-ce que le bonheur ?', texteInitiateur: 'Pour vous, qu\'est-ce que le bonheur ?', textePartenaire: 'Selon vous, quelle est sa définition du bonheur ?' },
      { slug: 'si_on_vous_offrait_le_metier_de_vos_reve', type: 'text', texte: 'Si on vous offrait le métier de vos rêves, sans aucune contrainte, lequel serait-il ?', texteInitiateur: 'Si on vous offrait le métier de vos rêves, sans aucune contrainte, lequel serait-il ?', textePartenaire: 'Selon vous, quel serait son métier de rêve ?' },
      { slug: 'qu_est_ce_que_vous_aimez_le_plus_en_vous', type: 'text', texte: 'Qu\'est-ce que vous aimez le plus en vous ?', texteInitiateur: 'Qu\'est-ce que vous aimez le plus en vous ?', textePartenaire: 'Selon, vous, qu\'est-ce qu\'elle/il aime le plus chez elle/lui ?' },
      { slug: 'sur_une_echelle_de_1_a_10_etes_vous_heur', type: 'echelle', texte: 'Sur une échelle de 1 à 10, êtes-vous heureux·se aujourd\'hui ?', texteInitiateur: 'Sur une échelle de 1 à 10, êtes-vous heureux·se aujourd\'hui ?', textePartenaire: 'Sur une échelle de 1 à 10, pensez-vous qu\'elle/il est heureux·se aujourd\'hui ?', min: 1, max: 10, labelMin: 'Pas vraiment', labelMax: 'Pleinement' },
      { slug: 'que_vous_manque_t_il', type: 'text', texte: 'Que vous manque-t-il ?', texteInitiateur: 'Que vous manque-t-il ?', textePartenaire: 'Que lui manque-t-il ?' },
      { slug: 'quels_sont_vos_petits_peches_gourmands', type: 'text', texte: 'Quels sont vos petits péchés gourmands  ?', texteInitiateur: 'Quels sont vos petits péchés gourmands  ?', textePartenaire: 'Quels sont ses petits péchés gourmands  ?' },
      { slug: 'quelles_sont_vos_plus_grandes_peurs', type: 'text', texte: 'Quelles sont vos plus grandes peurs ?', texteInitiateur: 'Quelles sont vos plus grandes peurs ?', textePartenaire: 'Quelles sont ses plus grandes peurs ?' },
      { slug: 'qu_est_ce_qui_vous_stresse_le_plus_dans', type: 'text', texte: 'Qu\'est-ce qui vous stresse le plus dans la vie ? (situations, lieux, personnes...)', texteInitiateur: 'Qu\'est-ce qui vous stresse le plus dans la vie ? (situations, lieux, personnes...)', textePartenaire: 'Qu\'est-ce qui le/la vous stresse le plus dans la vie ? (situations, lieux, personnes...)' },
      { slug: 'comment_se_manifeste_le_stress_chez_vous', type: 'text', texte: 'Comment se manifeste le stress chez vous ?', texteInitiateur: 'Comment se manifeste le stress chez vous ?', textePartenaire: 'Comment se manifeste le stress chez elle/lui ?' },
      { slug: 'qu_est_ce_qui_vous_motive', type: 'text', texte: 'Qu\'est-ce qui vous motive ?', texteInitiateur: 'Qu\'est-ce qui vous motive ?', textePartenaire: 'Qu\'est-ce qui la/le motive ?' },
      { slug: 'qu_est_ce_qui_vous_enerve', type: 'text', texte: 'Qu\'est-ce qui vous énerve ?', texteInitiateur: 'Qu\'est-ce qui vous énerve ?', textePartenaire: 'Qu\'est-ce qui l\'énerve ?' },
      { slug: 'qu_est_ce_qui_vous_calme', type: 'text', texte: 'Qu\'est-ce qui vous calme ?', texteInitiateur: 'Qu\'est-ce qui vous calme ?', textePartenaire: 'Qu\'est-ce qui la/le calme ?' },
      { slug: 'quel_est_votre_plat_prefere', type: 'text', texte: 'Quel est votre plat préféré ?', texteInitiateur: 'Quel est votre plat préféré ?', textePartenaire: 'Quel est son plat préféré ?' },
      { slug: 'quel_sont_vos_films_preferes', type: 'text', texte: 'Quel sont vos films préférés ?', texteInitiateur: 'Quel sont vos films préférés ?', textePartenaire: 'Quels sont ses films préféres ?' },
      { slug: 'quel_sont_vos_livres_preferes', type: 'text', texte: 'Quel sont vos livres préférés ?', texteInitiateur: 'Quel sont vos livres préférés ?', textePartenaire: 'Quels sont ses livres préféres ?' },
      { slug: 'quel_sont_vos_groupes_styles_de_musiques', type: 'text', texte: 'Quel sont vos groupes/styles de musiques préférés ?', texteInitiateur: 'Quel sont vos groupes/styles de musiques préférés ?', textePartenaire: 'Quel sont ses groupes/styles de musiques préférés ?' },
    ],
  },
  {
    slug: 'partenaire2', n: 2,
    titre: 'Partenaire 2',
    sousTitre: 'Connaissance de l\'autre',
    description: 'On croit connaître l\'autre par cœur. Ce module révèle les angles morts, avec tendresse.',
    emoji: '👁️', free: false, annuel: false,
    introTexte: '',
    outroTexte: '',
    questions: [
      { slug: 'comment_decririez_vous_l_autre_soyez_lib', type: 'text', texte: 'Comment décririez-vous l\'autre ? (soyez libre de décrire physiquement, parcours de vie, caractère, ...)', texteInitiateur: 'Comment décririez-vous l\'autre ? (soyez libre de décrire physiquement, parcours de vie, caractère, ...)', textePartenaire: 'Comment vous décririez-vous ? (soyez libre de décrire physiquement, parcours de vie, caractère, ...)' },
      { slug: 'quelles_sont_ses_grandes_qualites', type: 'text', texte: 'Quelles sont ses grandes qualités ?', texteInitiateur: 'Quelles sont ses grandes qualités ?', textePartenaire: 'Quelles sont vos grandes qualités ?' },
      { slug: 'quelle_est_sa_plus_grande_blessure_aband', type: 'text', texte: 'Quelle est sa plus grande blessure (abandon, trahison, rejet, humiliation, injustice, autre) ?', texteInitiateur: 'Quelle est sa plus grande blessure (abandon, trahison, rejet, humiliation, injustice, autre) ?', textePartenaire: 'Quelle est votre plus grande blessure (abandon, trahison, rejet, humiliation, injustice, autre) ?' },
      { slug: 'qu_est_ce_qui_le_ou_la_passionne', type: 'text', texte: 'Qu\'est-ce qui le ou la passionne ?', texteInitiateur: 'Qu\'est-ce qui le ou la passionne ?', textePartenaire: 'Qu\'est-ce qui vous passionne ?' },
      { slug: 'a_t_elle_il_un_but_dans_la_vie', type: 'text', texte: 'A t-elle/il un but dans la vie ?', texteInitiateur: 'A t-elle/il un but dans la vie ?', textePartenaire: 'Avez-vous un but dans la vie ?' },
      { slug: 'selon_vous_quelle_est_sa_definition_du_b', type: 'text', texte: 'Selon vous, quelle est sa définition du bonheur ?', texteInitiateur: 'Selon vous, quelle est sa définition du bonheur ?', textePartenaire: 'Pour vous, qu\'est-ce que le bonheur ?' },
      { slug: 'selon_vous_quel_serait_son_metier_de_rev', type: 'text', texte: 'Selon vous, quel serait son métier de rêve ?', texteInitiateur: 'Selon vous, quel serait son métier de rêve ?', textePartenaire: 'Si on vous offrait le métier de vos rêves, sans aucune contrainte, lequel serait-il ?' },
      { slug: 'selon_vous_qu_est_ce_qu_elle_il_aime_le', type: 'text', texte: 'Selon, vous, qu\'est-ce qu\'elle/il aime le plus chez elle/lui ?', texteInitiateur: 'Selon, vous, qu\'est-ce qu\'elle/il aime le plus chez elle/lui ?', textePartenaire: 'Qu\'est-ce que vous aimez le plus en vous ?' },
      { slug: 'sur_une_echelle_de_1_a_10_pensez_vous_qu', type: 'echelle', texte: 'Sur une échelle de 1 à 10, pensez-vous qu\'elle/il est heureux·se aujourd\'hui ?', texteInitiateur: 'Sur une échelle de 1 à 10, pensez-vous qu\'elle/il est heureux·se aujourd\'hui ?', textePartenaire: 'Sur une échelle de 1 à 10, êtes-vous heureux·se aujourd\'hui ?', min: 1, max: 10, labelMin: 'Pas vraiment', labelMax: 'Pleinement' },
      { slug: 'que_lui_manque_t_il', type: 'text', texte: 'Que lui manque-t-il ?', texteInitiateur: 'Que lui manque-t-il ?', textePartenaire: 'Que vous manque-t-il ?' },
      { slug: 'quels_sont_ses_petits_peches_gourmands', type: 'text', texte: 'Quels sont ses petits péchés gourmands  ?', texteInitiateur: 'Quels sont ses petits péchés gourmands  ?', textePartenaire: 'Quels sont vos petits péchés gourmands  ?' },
      { slug: 'quelles_sont_ses_plus_grandes_peurs', type: 'text', texte: 'Quelles sont ses plus grandes peurs ?', texteInitiateur: 'Quelles sont ses plus grandes peurs ?', textePartenaire: 'Quelles sont vos plus grandes peurs ?' },
      { slug: 'qu_est_ce_qui_le_la_vous_stresse_le_plus', type: 'text', texte: 'Qu\'est-ce qui le/la vous stresse le plus dans la vie ? (situations, lieux, personnes...)', texteInitiateur: 'Qu\'est-ce qui le/la vous stresse le plus dans la vie ? (situations, lieux, personnes...)', textePartenaire: 'Qu\'est-ce qui vous stresse le plus dans la vie ? (situations, lieux, personnes...)' },
      { slug: 'comment_se_manifeste_le_stress_chez_elle', type: 'text', texte: 'Comment se manifeste le stress chez elle/lui ?', texteInitiateur: 'Comment se manifeste le stress chez elle/lui ?', textePartenaire: 'Comment se manifeste le stress chez vous ?' },
      { slug: 'qu_est_ce_qui_la_le_motive', type: 'text', texte: 'Qu\'est-ce qui la/le motive ?', texteInitiateur: 'Qu\'est-ce qui la/le motive ?', textePartenaire: 'Qu\'est-ce qui vous motive ?' },
      { slug: 'qu_est_ce_qui_l_enerve', type: 'text', texte: 'Qu\'est-ce qui l\'énerve ?', texteInitiateur: 'Qu\'est-ce qui l\'énerve ?', textePartenaire: 'Qu\'est-ce qui vous énerve ?' },
      { slug: 'qu_est_ce_qui_la_le_calme', type: 'text', texte: 'Qu\'est-ce qui la/le calme ?', texteInitiateur: 'Qu\'est-ce qui la/le calme ?', textePartenaire: 'Qu\'est-ce qui vous calme ?' },
      { slug: 'quel_est_son_plat_prefere', type: 'text', texte: 'Quel est son plat préféré ?', texteInitiateur: 'Quel est son plat préféré ?', textePartenaire: 'Quel est votre plat préféré ?' },
      { slug: 'quels_sont_ses_films_preferes', type: 'text', texte: 'Quels sont ses films préféres ?', texteInitiateur: 'Quels sont ses films préféres ?', textePartenaire: 'Quel sont vos films préférés ?' },
      { slug: 'quels_sont_ses_livres_preferes', type: 'text', texte: 'Quels sont ses livres préféres ?', texteInitiateur: 'Quels sont ses livres préféres ?', textePartenaire: 'Quel sont vos livres préférés ?' },
      { slug: 'quel_sont_ses_groupes_styles_de_musiques', type: 'text', texte: 'Quel sont ses groupes/styles de musiques préférés ?', texteInitiateur: 'Quel sont ses groupes/styles de musiques préférés ?', textePartenaire: 'Quel sont vos groupes/styles de musiques préférés ?' },
    ],
  },
  {
    slug: 'couple', n: 3,
    titre: 'Notre couple',
    sousTitre: 'Ce qui vous unit',
    description: 'On dessine le « nous » : votre histoire, ce que vous construisez, ce que vous protégez.',
    emoji: '💑', free: false, annuel: false,
    introTexte: '',
    outroTexte: '',
    questions: [
      { slug: 'racontez_ici_votre_rencontre', type: 'text', texte: 'Racontez ici votre rencontre' },
      { slug: 'fermez_les_yeux_quelques_secondes_quels', type: 'text', texte: 'Fermez les yeux quelques secondes : quels moments forts de votre couple vous reviennent ?' },
      { slug: 'qu_est_ce_qui_vous_a_plu_chez_l_autre_au', type: 'text', texte: 'Qu\'est-ce qui vous a plu chez l\'autre au tout début ? (qualités, traits physiques, caractère)' },
      { slug: 'et_qu_est_ce_qui_vous_plait_aujourd_hui', type: 'text', texte: 'Et qu\'est-ce qui vous plaît, aujourd\'hui ? (ce n\'est pas toujours la même chose)' },
      { slug: 'qu_est_ce_que_l_autre_vous_apporte_dans', type: 'text', texte: 'Qu\'est-ce que l\'autre vous apporte dans votre vie ?' },
      { slug: 'qu_est_ce_qui_est_le_plus_difficile_a_ac', type: 'text', texte: 'Qu\'est-ce qui est le plus difficile à accepter chez l\'autre ? (caractère, attitudes, éducation...)' },
      { slug: 'comment_decririez_vous_votre_couple_aujo', type: 'text', texte: 'Comment décririez-vous votre couple aujourd\'hui ? (cocooning, fusionnel, indépendant, festif, passionné, pudique...)' },
      { slug: 'si_votre_couple_etait_un_animal_un_livre', type: 'text', texte: 'Si votre couple était un animal / un livre / une chanson / un film, lequel serait-il ? Pourquoi ?' },
      { slug: 'comment_vous_imaginez_vous_dans_5_ans_et', type: 'text', texte: 'Comment vous imaginez-vous dans 5 ans ? Et dans 20 ans ?' },
      { slug: 'qu_attendez_vous_de_l_autre', type: 'text', texte: 'Qu\'attendez-vous de l\'autre ?' },
      { slug: 'que_pensez_vous_que_l_autre_attend_de_vo', type: 'text', texte: 'Que pensez-vous que l\'autre attend de vous ?' },
      { slug: 'pensez_vous_etre_une_bonne_partenaire_en', type: 'text', texte: 'Pensez-vous être un·e bon·ne partenaire ? En quoi ?' },
      { slug: 'qu_est_ce_qu_un_couple_heureux_pour_vous', type: 'text', texte: 'Qu\'est-ce qu\'un couple heureux, pour vous ?' },
      { slug: 'a_votre_avis_qu_est_ce_qu_un_couple_heur', type: 'text', texte: 'À votre avis, qu\'est-ce qu\'un couple heureux selon l\'autre ?' },
      { slug: 'quel_regard_posez_vous_sur_la_vie_de_cou', type: 'text', texte: 'Quel regard posez-vous sur la vie de couple de vos parents ? Vous fait-elle envie ? Vous déçoit-elle ?' },
      { slug: 'y_a_t_il_des_modeles_de_couple_que_vous', type: 'text', texte: 'Y a-t-il des modèles de couple que vous aimeriez imiter (parents, amis, autres) ? En quoi ?' },
      { slug: 'selon_vous_quels_sont_les_3_principes_de', type: 'text', texte: 'Selon vous, quels sont les 3 principes de base pour une bonne entente dans un couple ?' },
    ],
  },
  {
    slug: 'quotidien', n: 4,
    titre: 'Notre quotidien',
    sousTitre: 'Travail & routines',
    description: 'La vie de tous les jours : répartition des tâches, loisirs, équilibre à deux.',
    emoji: '🏠', free: false, annuel: false,
    introTexte: '',
    outroTexte: '',
    questions: [
      { slug: 'depuis_combien_de_temps_vivez_vous_ensem', type: 'text', texte: 'Depuis combien de temps vivez-vous ensemble ?' },
      { slug: 'qui_fait_quoi_dans_votre_couple_les_repa', type: 'text', texte: 'Qui fait quoi dans votre couple ?  - les repas,  - les comptes,  - le ménage,  - les lessives, - le rangement,  - les projets vacances/sorties,  - le bricolage et les réparations,  - l\'entretien de la voiture, bricole/répare - les trajets pour les enfants - l\'administratif (gestion des contrats et impots)' },
      { slug: 'etes_vous_d_accord_avec_cette_organisati', type: 'text', texte: 'Êtes-vous d\'accord avec cette organisation ?' },
      { slug: 'trouvez_vous_que_c_est_equitablement_rep', type: 'text', texte: 'Trouvez vous que c\'est équitablement réparti ?' },
      { slug: 'est_ce_que_cela_est_source_de_disputes_o', type: 'text', texte: 'Est-ce que cela est source de disputes ou de frustration ?' },
      { slug: 'que_voudriez_vous_changer', type: 'text', texte: 'Que voudriez-vous changer ?' },
      { slug: 'qui_lance_les_conversations', type: 'text', texte: 'Qui lance les conversations ?' },
      { slug: 'qui_fait_la_tete_le_plus_ou_se_vexe_le_p', type: 'text', texte: 'Qui fait la tête le plus ou se vexe le plus ?' },
      { slug: 'qui_est_le_ou_la_plus_critique', type: 'text', texte: 'Qui est le ou la plus critique ?' },
      { slug: 'qui_est_le_plus_ou_la_plus_tetu_e', type: 'text', texte: 'Qui est le plus ou la plus têtu.e ?' },
      { slug: 'qui_est_le_plus_ou_la_plus_social_e', type: 'text', texte: 'Qui est le plus ou la plus social.e ?' },
      { slug: 'qui_motive_l_autre', type: 'text', texte: 'Qui motive l\'autre ?' },
      { slug: 'qui_console_l_autre', type: 'text', texte: 'Qui console l\'autre ?' },
      { slug: 'cote_loisirs_quelles_activites_faites_vo', type: 'text', texte: 'Côté loisirs, quelles activités faites-vous ? Et l\'autre ?' },
      { slug: 'avez_vous_un_loisir_en_commun', type: 'text', texte: 'Avez-vous un loisir en commun ?' },
      { slug: 'sortez_vous_a_quelle_frequence_seule_ou', type: 'text', texte: 'Sortez-vous ? À quelle fréquence ? Seul·e ou en couple ?' },
      { slug: 'avez_vous_suffisamment_de_temps_pour_etr', type: 'text', texte: 'Avez-vous suffisamment de temps pour être ensemble en tête-à-tête ?' },
      { slug: 'a_quelle_frequence_jugez_vous_necessaire', type: 'text', texte: 'À quelle fréquence jugez-vous nécessaire de vous accorder des moments d\'intimité à deux ?' },
      { slug: 'a_quelle_frequence_jugez_vous_necessaire_2', type: 'text', texte: 'À quelle fréquence jugez-vous nécessaire de vous accorder des moments seul·e ?' },
      { slug: 'qu_est_ce_qui_a_le_plus_change_depuis_le', type: 'text', texte: 'Qu\'est-ce qui a le plus changé depuis le début de votre relation ?' },
      { slug: 'qu_est_ce_qui_est_le_plus_difficile_dans', type: 'text', texte: 'Qu\'est-ce qui est le plus difficile dans la vie commune selon vous ?' },
    ],
  },
  {
    slug: 'projets', n: 5,
    titre: 'Nos projets',
    sousTitre: 'Argent & avenir',
    description: 'Argent, projets communs et rêves à construire ensemble.',
    emoji: '🚀', free: false, annuel: false,
    introTexte: '',
    outroTexte: '',
    questions: [
      { slug: 'etes_vous_plutot_econome_ou_depensierere', type: 'text', texte: 'Êtes-vous plutôt économe ou dépensier·ère ? Dans quels domaines surtout (loisirs, vêtements, nourriture, voyages) ?' },
      { slug: 'quand_vous_aviez_5_10_15_puis_20_ans_que', type: 'text', texte: 'Quand vous aviez 5, 10, 15 puis 20 ans, que rêviez-vous de faire dans la vie ?' },
      { slug: 'avez_vous_des_dettes_ou_des_engagements', type: 'text', texte: 'Avez-vous des dettes ou des engagements financiers importants ? (crédit, prêt étudiant, soutien à un·e proche...)' },
      { slug: 'quelle_est_votre_relation_emotionnelle_a', type: 'text', texte: 'Quelle est votre relation émotionnelle à l\'argent ? (il vous rassure, vous angoisse, vous est indifférent) D\'où vient ce rapport ?' },
      { slug: 'qui_gagne_le_plus_dans_votre_couple', type: 'text', texte: 'Qui gagne le plus, dans votre couple ?' },
      { slug: 'comment_envisagez_vous_l_organisation_fi', type: 'text', texte: 'Comment envisagez-vous l\'organisation financière à deux ? (comptes séparés, compte commun, modèle mixte, contribution proportionnelle)' },
      { slug: 'qui_prend_les_decisions_financieres_impo', type: 'text', texte: 'Qui prend les décisions financières importantes, dans votre modèle idéal ?' },
      { slug: 'y_a_t_il_des_depenses_que_vous_considere', type: 'text', texte: 'Y a-t-il des dépenses que vous considérez comme personnelles et non soumises à discussion ?' },
      { slug: 'si_l_une_de_vous_deux_gagne_nettement_pl', type: 'text', texte: 'Si l\'un·e de vous deux gagne nettement plus que l\'autre, comment l\'envisagez-vous ? Et si l\'un·e arrête temporairement de travailler (enfant, maladie, projet) ?' },
      { slug: 'que_represente_le_travail_dans_votre_vie', type: 'text', texte: 'Que représente le travail dans votre vie ?' },
      { slug: 'avez_vous_deja_envisage_de_suivre_l_autr', type: 'text', texte: 'Avez-vous déjà envisagé de suivre l\'autre dans le cadre d\'une mutation professionnelle ? Comment réagiriez-vous ?' },
      { slug: 'accepteriez_vous_que_l_autre_ne_travaill', type: 'text', texte: 'Accepteriez-vous que l\'autre ne travaille pas ?' },
      { slug: 'avez_vous_des_projets_financiers_a_moyen', type: 'text', texte: 'Avez-vous des projets financiers à moyen terme ? (achat immobilier, épargne, voyages, création d\'entreprise...)' },
      { slug: 'avez_vous_des_projets_de_couple_sorties', type: 'text', texte: 'Avez-vous des projets de couple ? (sorties, découvertes, travaux, décoration, déménagement, achat, vacances...)' },
      { slug: 'avez_vous_un_reve_fou_personnel_est_ce_r', type: 'text', texte: 'Avez-vous un rêve fou personnel ? Est-ce réalisable ? Comment / pourquoi ?' },
      { slug: 'imaginez_la_maison_de_vos_reves_et_decri', type: 'text', texte: 'Imaginez la maison de vos rêves et décrivez-la (ville, style, couleurs, matériaux, atmosphère)' },
      { slug: 'quel_projet_de_couple_pourriez_vous_imag', type: 'text', texte: 'Quel projet de couple pourriez-vous imaginer ensemble ?' },
    ],
  },
  {
    slug: 'famille', n: 6,
    titre: 'La famille',
    sousTitre: 'Famille & enfants',
    description: 'Vos familles d\'origine, vos envies (ou non) d\'enfants, vos convictions.',
    emoji: '👪', free: false, annuel: false,
    introTexte: '',
    outroTexte: '',
    questions: [
      { slug: 'etes_vous_plutot_fete_de_famille_ou_loup', type: 'text', texte: 'Êtes-vous plutôt fête de famille ou loup solitaire ?' },
      { slug: 'qu_est_ce_que_vous_appreciez_le_plus_dan', type: 'text', texte: 'Qu\'est-ce que vous appréciez le plus dans votre famille ?' },
      { slug: 'qu_est_ce_qui_vous_agace_dans_votre_fami', type: 'text', texte: 'Qu\'est-ce qui vous agace, dans votre famille ?' },
      { slug: 'quelles_sont_les_plus_belles_valeurs_que', type: 'text', texte: 'Quelles sont les plus belles valeurs que vous avez reçues ?' },
      { slug: 'quelles_qualites_avez_vous_heritees_de_v', type: 'text', texte: 'Quelles qualités avez-vous héritées de votre père ? De votre mère ?' },
      { slug: 'quels_defauts_avez_vous_herites_de_votre', type: 'text', texte: 'Quels défauts avez-vous hérités de votre père ? De votre mère ?' },
      { slug: 'comment_decririez_vous_l_education_que_v', type: 'text', texte: 'Comment décririez-vous l\'éducation que vous avez reçue ? (stricte, tolérante, communicante, à l\'écoute, affectueuse, exigeante, autoritaire, protectrice, distante, joyeuse, permissive, punitive, austère, conflictuelle, festive, sereine, sportive, excessive...)' },
      { slug: 'voulez_vous_avoir_des_enfants_depuis_com', type: 'text', texte: 'Voulez-vous avoir des enfants ? Depuis combien de temps avez-vous cette certitude ? Avez-vous déjà eu des doutes ? Lesquels ?' },
      { slug: 'si_oui_combien_et_dans_quel_delai_ideale', type: 'text', texte: 'Si oui, combien ? Et dans quel délai idéalement ? Y a-t-il un événement ou une situation qui vous semble être le bon moment ?' },
      { slug: 'si_non_ou_si_vous_n_etes_pas_sure_qu_est', type: 'text', texte: 'Si non, ou si vous n\'êtes pas sûr·e, qu\'est-ce qui vous retient ? Est-ce une position définitive ou encore ouverte ?' },
      { slug: 'comment_imaginez_vous_l_education_que_vo', type: 'text', texte: 'Comment imaginez-vous l\'éducation que vous donnerez à vos enfants ? (adjectifs de la section éducation reçue, ou vos propres mots)' },
      { slug: 'qui_s_occupe_des_enfants_au_quotidien_ga', type: 'text', texte: 'Qui s\'occupe des enfants au quotidien ? (garde partagée, rôle de chacun·e, place du travail, aide extérieure)' },
      { slug: 'y_a_t_il_des_sujets_sur_lesquels_vous_se', type: 'text', texte: 'Y a-t-il des sujets sur lesquels vous sentez déjà que vous ne serez pas d\'accord ? (religion, école publique ou privée, écrans, discipline, alimentation)' },
      { slug: 'avez_vous_une_religion_ou_une_pratique_s', type: 'text', texte: 'Avez-vous une religion ou une pratique spirituelle ? (pratiquant·e, croyant·e non pratiquant·e, agnostique, athée, autre)' },
      { slug: 'quelle_place_tient_la_religion_dans_votr', type: 'text', texte: 'Quelle place tient la religion dans votre vie au quotidien ? (fêtes religieuses, alimentation, prière, rites de passage)' },
      { slug: 'et_dans_votre_famille_d_origine_quelle_p', type: 'text', texte: 'Et dans votre famille d\'origine, quelle place tenait-elle ? Qu\'avez-vous envie de conserver ? De laisser de côté ?' },
      { slug: 'comment_envisagez_vous_la_transmission_r', type: 'text', texte: 'Comment envisagez-vous la transmission religieuse aux enfants ? (éducation religieuse, aucune, les laisser choisir)' },
      { slug: 'y_a_t_il_des_rituels_religieux_ou_spirit', type: 'text', texte: 'Y a-t-il des rituels religieux ou spirituels qui vous tiennent à cœur pour le couple ? (cérémonie, bénédiction, fêtes, jeûne)' },
      { slug: 'ou_aimeriez_vous_vivre_idealement_ville', type: 'text', texte: 'Où aimeriez-vous vivre, idéalement ? (ville, campagne, banlieue, étranger) Pourquoi ?' },
      { slug: 'seriez_vous_prete_a_suivre_l_autre_dans', type: 'text', texte: 'Seriez-vous prêt·e à suivre l\'autre dans un déménagement important ? Dans quelles conditions ?' },
      { slug: 'quelle_est_votre_relation_a_la_famille_d', type: 'text', texte: 'Quelle est votre relation à la famille d\'origine ? La proximité géographique compte-t-elle pour vous ?' },
      { slug: 'y_a_t_il_des_endroits_ou_vous_refuseriez', type: 'text', texte: 'Y a-t-il des endroits où vous refuseriez de vivre ?' },
      { slug: 'si_vos_reponses_ne_coincident_pas_quelle', type: 'text', texte: 'Si vos réponses ne coïncident pas, quelle place laissez-vous à ce désaccord ? (négociable, rédhibitoire, pas encore réfléchi)' },
    ],
  },
  {
    slug: 'communication', n: 7,
    titre: 'Nos modes de communication',
    sousTitre: 'Se parler, s\'écouter',
    description: 'Comment vous vous exprimez, vous écoutez, et vous manifestez votre tendresse.',
    emoji: '💬', free: false, annuel: false,
    introTexte: '',
    outroTexte: '',
    questions: [
      { slug: 'vous_arrive_t_il_de_vous_raconter_vos_jo', type: 'text', texte: 'Vous arrive-t-il de vous raconter vos journées ? De quoi parlez-vous ?' },
      { slug: 'parlez_vous_des_emotions_ressenties_joie', type: 'text', texte: 'Parlez-vous des émotions ressenties (joie, tristesse, colère) ?' },
      { slug: 'etes_vous_capable_d_exprimer_a_l_autre_v', type: 'text', texte: 'Êtes-vous capable d\'exprimer à l\'autre vos besoins (compliments, gestes tendres, encouragements, aide) ?' },
      { slug: 'comment_et_quand_le_faites_vous_phrases', type: 'text', texte: 'Comment et quand le faites-vous ? (phrases claires, plaintes, attentes non exprimées, disputes, bouderies...)' },
      { slug: 'comment_l_autre_reagit_iel_selon_vous', type: 'text', texte: 'Comment l\'autre réagit-iel, selon vous ?' },
      { slug: 'et_vous_comment_reagissez_vous_quand_l_a', type: 'text', texte: 'Et vous, comment réagissez-vous quand l\'autre s\'exprime ?' },
      { slug: 'avez_vous_des_sujets_tabous_entre_vous_p', type: 'text', texte: 'Avez-vous des sujets tabous entre vous ? Pourquoi ? Que se passerait-il si vous en parliez ?' },
      { slug: 'avez_vous_peur_du_regard_ou_du_jugement', type: 'text', texte: 'Avez-vous peur du regard ou du jugement de l\'autre ?' },
      { slug: 'quelles_seraient_les_conditions_ideales', type: 'text', texte: 'Quelles seraient les conditions idéales pour en parler ?' },
      { slug: 'avez_vous_des_angoisses_que_vous_aimerie', type: 'text', texte: 'Avez-vous des angoisses que vous aimeriez voir disparaître ? En parler à l\'autre serait-il un bon moyen de vous y aider ?' },
      { slug: 'arrivez_vous_a_aborder_ensemble_vos_beso', type: 'text', texte: 'Arrivez-vous à aborder ensemble vos besoins et vos attentes sur les questions de sexualité ?' },
      { slug: 'comment_etes_vous_physiquement_quand_vou', type: 'text', texte: 'Comment êtes-vous physiquement quand vous communiquez avec l\'autre ?' },
      { slug: 'vous_regardez_vous_dans_les_yeux_quand_v', type: 'text', texte: 'Vous regardez-vous dans les yeux quand vous vous parlez ?' },
      { slug: 'vous_arrive_t_il_de_toucher_l_autre_pend', type: 'text', texte: 'Vous arrive-t-il de toucher l\'autre pendant vos conversations (main, épaule) ?' },
      { slug: 'exprimez_vous_votre_tendresse_a_l_egard', type: 'text', texte: 'Exprimez-vous votre tendresse à l\'égard de l\'autre ? Quand et comment, en privé et en public ?' },
      { slug: 'quels_sont_selon_vous_les_besoins_et_att', type: 'text', texte: 'Quels sont, selon vous, les besoins et attentes de l\'autre à ce sujet, en privé et en public ?' },
      { slug: 'etes_vous_satisfaite_des_marques_d_atten', type: 'text', texte: 'Êtes-vous satisfait·e des marques d\'attention de l\'autre à votre égard (privé / public) ?' },
      { slug: 'comment_manifestez_vous_votre_amour_a_l', type: 'text', texte: 'Comment manifestez-vous votre amour à l\'autre ? Et l\'autre, que fait-iel selon vous ?' },
      { slug: 'y_a_t_il_des_marques_d_affection_de_l_au', type: 'text', texte: 'Y a-t-il des marques d\'affection de l\'autre auxquelles vous n\'aviez jamais porté attention ?' },
      { slug: 'apres_cet_inventaire_est_ce_que_vous_com', type: 'text', texte: 'Après cet inventaire, est-ce que vous communiquez bien ? Que pouvez-vous améliorer ?' },
      { slug: 'quel_code_pourriez_vous_inventer_pour_si', type: 'text', texte: 'Quel code pourriez-vous inventer pour signaler « ce n\'est pas le moment » ou « il faut qu\'on parle » ?' },
    ],
  },
  {
    slug: 'disputes', n: 8,
    titre: 'Nos disputes',
    sousTitre: 'Désamorcer, grandir',
    description: 'Comprendre vos disputes pour mieux les traverser, et en sortir grandis.',
    emoji: '⚡', free: false, annuel: false,
    introTexte: '',
    outroTexte: '',
    questions: [
      { slug: 'a_propos_de_quoi_vous_disputez_vous', type: 'text', texte: 'À propos de quoi vous disputez-vous ?' },
      { slug: 'quand_cela_se_manifeste_t_il', type: 'text', texte: 'Quand cela se manifeste-t-il ?' },
      { slug: 'comment_cela_se_passe_t_il_la_plupart_du', type: 'text', texte: 'Comment cela se passe-t-il la plupart du temps ? Comment le vivez-vous ?' },
      { slug: 'vous_disputez_vous_souvent_comment_comme', type: 'text', texte: 'Vous disputez-vous souvent ? Comment commencent, puis se terminent vos disputes ?' },
      { slug: 'comment_trouvez_vous_des_solutions_satis', type: 'text', texte: 'Comment trouvez-vous des solutions satisfaisantes à deux en cas de désaccord ?' },
      { slug: 'qui_est_a_l_initiative_de_la_reconciliat', type: 'text', texte: 'Qui est à l\'initiative de la réconciliation, en général ?' },
      { slug: 'les_disputes_aboutissent_elles_a_des_ame', type: 'text', texte: 'Les disputes aboutissent-elles à des améliorations ?' },
      { slug: 'comment_etes_vous_sures_que_vous_vous_et', type: 'text', texte: 'Comment êtes-vous sûr·e·s que vous vous êtes vraiment pardonné·e·s ?' },
      { slug: 'l_une_de_vous_deux_cherche_t_iel_toujour', type: 'text', texte: 'L\'un·e de vous deux cherche-t-iel toujours à avoir raison ?' },
      { slug: 'l_une_ou_l_autre_a_t_iel_tendance_a_mono', type: 'text', texte: 'L\'un·e ou l\'autre a-t-iel tendance à monopoliser la parole ?' },
      { slug: 'aimeriez_vous_vous_disputer_moins_souven', type: 'text', texte: 'Aimeriez-vous vous disputer moins souvent ?' },
      { slug: 'exercice_a_tour_de_role_qu_est_ce_qui_vo', type: 'text', texte: 'Exercice : à tour de rôle, qu\'est-ce qui vous vient à l\'esprit quand vous pensez à ce qui vous met en colère ?' },
      { slug: 'exercice_de_reformulation_reprenez_un_re', type: 'text', texte: 'Exercice de reformulation : reprenez un reproche en vous mettant à la place de l\'autre — qu\'est-ce que ça change dans votre perception ?' },
      { slug: 'avez_vous_reussi_a_appliquer_les_regles', type: 'text', texte: 'Avez-vous réussi à appliquer les règles de communication harmonieuse (écoute active, sourire, regard) pendant cet exercice ?' },
      { slug: 'bilan_apres_une_dispute_qu_avez_vous_com', type: 'text', texte: 'Bilan après une dispute : qu\'avez-vous compris ? À quoi vous engagez-vous désormais ?' },
    ],
  },
  {
    slug: 'cdd', n: 9,
    titre: 'Notre CDD de couple',
    sousTitre: 'Votre contrat à durée déterminée',
    description: 'L\'aboutissement : vos engagements, vos vœux, votre contrat à re-signer chaque année.',
    emoji: '📜', free: false, annuel: false,
    introTexte: '',
    outroTexte: '',
    questions: [
      { slug: 'qu_est_ce_qui_est_important_pour_vous_et', type: 'text', texte: 'Qu\'est-ce qui est important pour vous et pour votre couple ? À quoi vous engagez-vous ? À quoi renoncez-vous ?' },
      { slug: 'd_apres_toutes_ces_questions_quelles_son', type: 'text', texte: 'D\'après toutes ces questions, quelles sont vos règles de couple au quotidien ? (indispensable / souhaitable / négociable / inacceptable)' },
      { slug: 'comment_vivez_vous_l_engagement', type: 'text', texte: 'Comment vivez-vous l\'engagement ?' },
      { slug: 'qui_a_voulu_voudrait_se_marier_en_premie', type: 'text', texte: 'Qui a voulu / voudrait se marier en premier ? Pour quelles raisons ?' },
      { slug: 'que_pensez_vous_que_le_mariage_va_change', type: 'text', texte: 'Que pensez-vous que le mariage va changer pour votre couple ?' },
      { slug: 'quelles_peurs_eventuelles_pensez_vous_va', type: 'text', texte: 'Quelles peurs éventuelles pensez-vous vaincre avec le mariage ?' },
      { slug: 'que_veut_dire_pour_vous_s_engager', type: 'text', texte: 'Que veut dire pour vous « s\'engager » ?' },
      { slug: 'quelle_est_selon_vous_la_plus_belle_preu', type: 'text', texte: 'Quelle est, selon vous, la plus belle preuve d\'engagement ?' },
      { slug: 'quels_sont_vos_souhaits_pour_l_avenir', type: 'text', texte: 'Quels sont vos souhaits pour l\'avenir ?' },
      { slug: 'de_quelle_maniere_souhaitez_vous_decouvr', type: 'text', texte: 'De quelle manière souhaitez-vous découvrir les vœux de l\'autre ? (par la poste, en privé, ensemble la veille...)' },
    ],
  },
  {
    slug: 'bac', n: 10,
    titre: 'Le BAC love (bilan annuel de couple)',
    sousTitre: 'Bilan annuel de couple',
    description: 'Chaque année, faites le bilan de votre couple — et suivez votre évolution dans le temps.',
    emoji: '🎓', free: false, annuel: true,
    introTexte: '',
    outroTexte: '',
    questions: [
      { slug: 'quels_sont_les_points_positifs_que_vous', type: 'text', texte: 'Quels sont les points positifs que vous pouvez noter concernant votre couple, sur l\'année écoulée ?' },
      { slug: 'quels_moments_ont_ete_plus_difficiles_a', type: 'text', texte: 'Quels moments ont été plus difficiles à vivre ?' },
      { slug: 'qu_est_ce_que_vous_changeriez', type: 'text', texte: 'Qu\'est-ce que vous changeriez ?' },
      { slug: 'avez_vous_pu_exprimer_vos_besoins_et_att', type: 'text', texte: 'Avez-vous pu exprimer vos besoins et attentes vis-à-vis de l\'autre ?' },
      { slug: 'quels_ajustements_vous_engagez_vous_a_fa', type: 'text', texte: 'Quels ajustements vous engagez-vous à faire pour l\'autre ? Et l\'autre, à quoi s\'engage-t-iel pour vous ?' },
      { slug: 'avez_vous_un_projet_en_cours_qui_fait_qu', type: 'text', texte: 'Avez-vous un projet en cours ? Qui fait quoi, quelles sont les avancées et les échéances ?' },
      { slug: 'voulez_vous_lancer_de_nouveaux_projets_p', type: 'text', texte: 'Voulez-vous lancer de nouveaux projets pour l\'année à venir ? Qui va faire quoi, à quelle échéance ?' },
      { slug: 'de_quoi_etes_vous_fiere_cette_annee', type: 'text', texte: 'De quoi êtes-vous fier·e cette année ?' },
      { slug: 'a_quel_sujet_eprouvez_vous_de_la_gratitu', type: 'text', texte: 'À quel sujet éprouvez-vous de la gratitude envers l\'autre ?' },
      { slug: 'quels_sont_vos_vux_pour_votre_couple_cet', type: 'text', texte: 'Quels sont vos vœux pour votre couple, cette année ?' },
    ],
  },
]

export function getModuleBySlug(slug: string): ModuleInfo | undefined {
  return MODULES.find(m => m.slug === slug)
}

export function moduleTitre(m: ModuleInfo, prenomPartenaire1?: string | null, prenomPartenaire2?: string | null): string {
  if (m.slug === 'partenaire1') return prenomPartenaire1 || m.titre
  if (m.slug === 'partenaire2') return prenomPartenaire2 || m.titre
  return m.titre
}

export function questionTexte(q: ModuleInfo['questions'][number], role?: string | null): string {
  if (role === 'initiateur' && q.texteInitiateur) return q.texteInitiateur
  if (role === 'partenaire' && q.textePartenaire) return q.textePartenaire
  return q.texte
}

export const MODULE_ORDER = MODULES.map(m => m.slug)
