import type { ConclusionSlug, ConclusionTexte, ModuleInfo } from '@/types'

type Conclusion = Record<ConclusionSlug, ConclusionTexte>

/**
 * Questions de fin de module utilisées quand un module n'a pas encore les siennes
 * (modules personnalisés créés depuis l'admin, notamment).
 */
export const CONCLUSION_PAR_DEFAUT: Conclusion = {
  apprentissage: {
    label: "Qu'est-ce qui t'a marqué·e dans ce module ?",
    placeholder: "Ce qui t'a marqué·e…",
    label_en: 'What stood out to you in this module?',
    placeholder_en: 'What stood out to you…',
  },
  surprise: {
    label: "Qu'est-ce qui t'a ému·e ?",
    placeholder: "Ce qui t'a ému·e…",
    label_en: 'What moved you?',
    placeholder_en: 'What moved you…',
  },
}

export function conclusionDuModule(m: ModuleInfo): Conclusion {
  return m.conclusion ?? CONCLUSION_PAR_DEFAUT
}

export const MODULES: ModuleInfo[] = [
  {
    slug: 'toi', n: 1,
    titre: 'Toi et Moi', titre_en: 'You and Me',
    sousTitre: 'Se (re)découvrir', sousTitre_en: '(Re)discovering each other',
    description: "On croit se connaître par cœur. Ce module révèle les angles morts, avec tendresse.",
    description_en: 'You think you know each other by heart. This module gently reveals the blind spots.',
    emoji: '👁️', free: true,
    // Questions de fin de module : à personnaliser pour ce module.
    conclusion: CONCLUSION_PAR_DEFAUT,
    questions: [
      { slug: 'bonheur_def', type: 'text', texte: 'Quelle est ta définition du bonheur ?', texte_en: 'What is your definition of happiness?' },
      { slug: 'qualites_preferees', type: 'text', texte: "Quelles sont les qualités que tu préfères chez l'autre ?", hint: 'Donne entre 3 et 5 qualités', texte_en: 'What qualities do you like most about your partner?', hint_en: 'Give between 3 and 5 qualities' },
      { slug: 'apporte', type: 'text', texte: "Qu'est-ce que l'autre t'apporte dans la vie ?", texte_en: 'What does your partner bring to your life?' },
      { slug: 'trois_mots_moi', type: 'text', texte: 'Si tu devais te décrire toi-même en 3 mots, lesquels choisirais-tu ?', texte_en: 'If you had to describe yourself in 3 words, which would you choose?' },
      { slug: 'trois_mots_autre', type: 'text', texte: "Si tu devais décrire l'autre en 3 mots, lesquels choisirais-tu ?", texte_en: 'If you had to describe your partner in 3 words, which would you choose?' },
      { slug: 'echelle_bonheur', type: 'text', texte: 'Sur une échelle de 1 à 10, à combien estimes-tu ton niveau de bonheur en ce moment ? Pourquoi ?', texte_en: 'On a scale of 1 to 10, how would you rate your happiness level right now? Why?' },
      { slug: 'echelle_bonheur_autre', type: 'text', texte: "À ton avis, quel chiffre l'autre donnerait-il à son propre niveau de bonheur, là maintenant ?", texte_en: "In your opinion, what number would your partner give their own happiness level, right now?" },
      { slug: 'reves_10_20_ans', type: 'text', texte: 'Quand tu avais 10 ans puis 20 ans, au-delà du métier que tu voulais exercer, quel rêve avais-tu dans la vie ?', texte_en: 'When you were 10, then 20, beyond the career you wanted, what dream did you have for your life?' },
      { slug: 'reves_10_20_ans_autre', type: 'text', texte: "Penses-tu connaître les rêves de l'autre à 10 et 20 ans ? Essaie d'imaginer", texte_en: "Do you think you know your partner's dreams at 10 and 20? Try to imagine." },
      { slug: 'metier_reve', type: 'text', texte: "Si on t'offrait le métier de tes rêves, là maintenant, sans aucune contrainte de temps, d'argent, de diplôme, de lieu, lequel serait-il ?", texte_en: 'If you were offered your dream job right now, with no constraints of time, money, qualifications, or location, what would it be?' },
      { slug: 'metier_reve_autre', type: 'text', texte: "Selon toi, quel serait le métier de rêve de l'autre ?", texte_en: "In your opinion, what would your partner's dream job be?" },
      { slug: 'fierte', type: 'text', texte: 'De quoi es-tu très fier·e dans ta vie ?', texte_en: 'What are you very proud of in your life?' },
      { slug: 'fierte_autre', type: 'text', texte: "Selon toi, de quoi l'autre est fier·e ?", texte_en: 'In your opinion, what is your partner proud of?' },
    ],
  },
  {
    slug: 'nous', n: 2,
    titre: 'Nous', titre_en: 'Us',
    sousTitre: 'Notre histoire', sousTitre_en: 'Our story',
    description: "On revient sur ce qu'on a construit : la rencontre, les moments forts, ce qui nous fait tenir.",
    description_en: "Let's look back at what you've built together: how you met, the milestones, what keeps you going.",
    emoji: '💑', free: false,
    // Questions de fin de module : à personnaliser pour ce module.
    conclusion: CONCLUSION_PAR_DEFAUT,
    questions: [
      { slug: 'rencontre', type: 'text', texte: 'Raconte ici votre rencontre ? Quels sont les moments clefs du tout début ?', texte_en: 'Tell the story of how you met. What were the key moments at the very beginning?' },
      { slug: 'moments_forts', type: 'text', texte: 'Quels sont les 3 ou 4 moments forts du début de votre couple ?', texte_en: 'What are the 3 or 4 milestones from the beginning of your relationship?' },
      { slug: 'craquer_moi', type: 'text', texte: "Qu'est-ce qui t'a séduit chez l'autre, la toute première fois ?", texte_en: 'What attracted you to your partner, the very first time?' },
      { slug: 'plait_aujourdhui', type: 'text', texte: "Et qu'est-ce qui te plaît aujourd'hui ?", texte_en: 'And what do you like about your partner today?' },
      { slug: 'serieux', type: 'text', texte: 'Quel est le moment où tu as su que « c\'était du sérieux » ?', texte_en: 'When did you know it was "serious"?' },
      { slug: 'decision_folle', type: 'text', texte: 'Quelle est la décision la plus « folle » que vous ayez prise ensemble ?', texte_en: 'What is the "craziest" decision you have made together?' },
      { slug: 'toujours_ensemble', type: 'text', texte: "Qu'est-ce qui fait que vous êtes toujours ensemble, selon toi ?", texte_en: 'In your opinion, what keeps you together?' },
      { slug: 'amis_decrivent', type: 'text', texte: 'Comment vos amis proches décrivent votre couple ?', texte_en: 'How do your close friends describe your relationship?' },
      { slug: 'futur_10_ans', type: 'text', texte: 'Comment imagines-tu votre couple dans 10 ans ?', texte_en: 'How do you picture your relationship in 10 years?' },
      { slug: 'futur_20_ans', type: 'text', texte: 'Et dans 20 ans ?', texte_en: 'And in 20 years?' },
    ],
  },
  {
    slug: 'quotidien', n: 3,
    titre: 'Le quotidien', titre_en: 'Everyday Life',
    sousTitre: 'La vie commune', sousTitre_en: 'Life together',
    description: "La charge mentale, la répartition des tâches, les petits gestes : ce qui fait un quotidien qui tient.",
    description_en: 'The mental load, how you split tasks, the small gestures: what makes an everyday life that holds together.',
    emoji: '🏠', free: false,
    questions: [
      { slug: 'depuis_quand', type: 'text', texte: 'Depuis combien de temps vivez-vous ensemble ?', texte_en: 'How long have you been living together?' },
      {
        slug: 'repartition_grille', type: 'grille', colonnesMoiToi: true,
        texte: "Qui s'occupe majoritairement de chacune de ces tâches ? Coche une case par ligne.",
        texte_en: 'Who mostly takes care of each of these tasks? Check one box per row.',
        options: ['Moi', 'Toi', 'Nous deux', 'Personne (ou externalisé)'],
        options_en: ['Me', 'You', 'Both of us', 'Nobody (or outsourced)'],
        lignes: [
          'Les courses', 'La vaisselle', 'Les repas', 'Les comptes / le suivi des dépenses', 'Le ménage',
          'Les lessives', 'Le repassage', 'Le rangement quotidien', 'Les réparations et le petit bricolage',
          "L'entretien de la voiture", 'Les trajets des enfants', 'Les soins aux animaux',
          'Les tâches administratives', "L'organisation des vacances",
        ],
        lignes_en: [
          'Groceries', 'Dishes', 'Cooking', 'Budgeting / tracking expenses', 'Cleaning',
          'Laundry', 'Ironing', 'Daily tidying', 'Repairs and small DIY jobs',
          'Car maintenance', "Driving the kids around", 'Caring for pets',
          'Paperwork', 'Planning vacations',
        ],
      },
      { slug: 'organisation_convient', type: 'text', texte: 'Est-ce que cette organisation vous convient ?', texte_en: 'Does this arrangement work for you?' },
      { slug: 'changer_repartition', type: 'text', texte: "Qu'est-ce que vous aimeriez changer dans cette répartition ?", texte_en: 'What would you like to change about how things are split?' },
      { slug: 'geste_touche', type: 'text', texte: "Quel est le geste ou l'attention qui te touche le plus, au quotidien, de la part de l'autre ?", texte_en: 'What gesture or thoughtful act from your partner touches you most in everyday life?' },
      { slug: 'loisir_solo', type: 'text', texte: 'Quel loisir aimerais-tu prendre le temps de faire en solo ?', texte_en: 'What hobby would you like to make time for on your own?' },
      { slug: 'loisir_couple', type: 'text', texte: 'Quel loisir aimerais-tu prendre le temps de faire en couple ?', texte_en: 'What hobby would you like to make time for as a couple?' },
      { slug: 'temps_deux', type: 'text', texte: 'Selon toi, est-ce que vous arrivez à avoir suffisamment de temps ensemble en tête-à-tête ?', texte_en: 'In your opinion, do you manage to have enough one-on-one time together?' },
    ],
    conclusion: {
      apprentissage: {
        label: 'Quels changements pouvez-vous engager suite à ce module au niveau du partage des tâches ou de vos loisirs solo / en duo ?',
        placeholder: 'Les changements que vous pouvez engager…',
        label_en: 'What changes can you make after this module, in how you share tasks or in your solo / couple hobbies?',
        placeholder_en: 'The changes you can make…',
      },
      surprise: {
        label: "Que retenez-vous de ce module ? Qu'est-ce qui vous a surpris ?",
        placeholder: 'Ce que vous retenez, ce qui vous a surpris…',
        label_en: 'What do you take away from this module? What surprised you?',
        placeholder_en: 'What you take away, what surprised you…',
      },
    },
  },
  {
    slug: 'projets', n: 4,
    titre: 'Argent et projets', titre_en: 'Money and plans',
    sousTitre: 'Argent, travail, avenir', sousTitre_en: 'Money, work, the future',
    description: "L'argent, le travail, les rêves à deux : des sujets qu'on esquive trop souvent, à poser sur la table.",
    description_en: "Money, work, shared dreams: topics we too often dodge — time to put them on the table.",
    emoji: '🎯', free: false,
    conclusion: {
      apprentissage: {
        label: 'Allez-vous changer quelque chose suite à ce module et si oui, quoi ?',
        placeholder: 'Ce que vous allez changer…',
        label_en: 'Will you change anything after this module? If so, what?',
        placeholder_en: 'What you will change…',
      },
      surprise: {
        label: "Qu'est-ce qui vous a étonné ou marqué ?",
        placeholder: 'Ce qui vous a étonné ou marqué…',
        label_en: 'What surprised you or stood out to you?',
        placeholder_en: 'What surprised you or stood out…',
      },
    },
    questions: [
      { slug: 'econome_depensier', type: 'text', texte: "Êtes-vous plutôt économe ou dépensier·ère ? Dans quels domaines surtout (loisirs, vêtements, nourriture, voyages) ?", texte_en: 'Are you more of a saver or a spender? In which areas especially (leisure, clothes, food, travel)?' },
      { slug: 'postes_depense_perso', type: 'text', texte: "Quels sont les postes de dépense qui sont importants pour vous à titre personnel (en dehors de ce qui est vital, charges et frais de logement/alimentation) ? Par exemple, je veux pouvoir garder un peu de côté pour m'acheter des vêtements ou sortir avec des amis, voyager, ...", texte_en: "Which spending categories matter to you personally (beyond essentials, bills, housing and food)? For example: I want to be able to set a little aside to buy clothes, go out with friends, travel, ..." },
      { slug: 'comptes_bancaires', type: 'text', texte: 'Avez-vous un compte bancaire perso, un compte commun, les deux ? Comment gérez-vous les dépenses communes ?', texte_en: 'Do you have a personal bank account, a joint account, or both? How do you handle shared expenses?' },
      { slug: 'comptes_satisfaction', type: 'text', texte: "Est-ce que cela vous convient ? Qu'aimeriez-vous changer ou améliorer ?", texte_en: 'Does this work for you? What would you like to change or improve?' },
      { slug: 'securite_financiere', type: 'text', texte: 'La sécurité financière est-elle un sujet pour vous ? Ressentez-vous la peur de manquer ?', texte_en: 'Is financial security an issue for you? Do you feel a fear of not having enough?' },
      { slug: 'relation_argent', type: 'text', texte: "Quelle est votre relation émotionnelle à l'argent ? Est-ce que ça vous rassure, vous angoisse, vous est indifférent, ... D'où vient ce rapport ?", texte_en: 'What is your emotional relationship with money? Does it reassure you, stress you out, leave you indifferent, ... Where does that come from?' },
      { slug: 'qui_gagne_plus', type: 'text', texte: 'Qui gagne le plus dans votre couple ? Comment le vivez-vous ?', texte_en: 'Who earns more in your relationship? How do you feel about it?' },
      { slug: 'decisions_a_deux', type: 'text', texte: 'Est-ce que les décisions financières sont prises à deux ? Si non, pourquoi ?', texte_en: 'Are financial decisions made together? If not, why?' },
      { slug: 'son_compte_arreter', type: 'text', texte: "Envisageriez-vous un jour de vous mettre à votre compte ou d'arrêter de travailler ?", texte_en: 'Would you ever consider becoming self-employed or stopping work?' },
      { slug: 'demenager', type: 'text', texte: 'Avez-vous déjà envisagé de déménager, et de changer de ville/pays ? Pourquoi et dans quelles conditions idéales le feriez-vous ?', texte_en: 'Have you ever considered moving to another city or country? Why, and under what ideal conditions would you do it?' },
      { slug: 'maison_reve', type: 'text', texte: 'Imaginez la maison de vos rêves et décrivez-la.', texte_en: 'Picture your dream home and describe it.' },
      { slug: 'reve_fou', type: 'text', texte: 'Avez-vous un rêve fou personnel ? Est-ce réalisable ? Comment / pourquoi ?', texte_en: 'Do you have a wild personal dream? Is it achievable? How / why?' },
    ],
  },
  {
    slug: 'famille', n: 5,
    titre: 'La famille', titre_en: 'Family',
    sousTitre: "D'où l'on vient, ce qu'on transmet", sousTitre_en: 'Where we come from, what we pass on',
    description: "L'éducation reçue, les enfants, la religion, le lieu de vie : ce qui vient de nos familles et ce qu'on choisit d'en garder.",
    description_en: 'The upbringing we received, children, religion, where to live: what comes from our families, and what we choose to keep.',
    emoji: '🌳', free: false,
    // Questions de fin de module : à personnaliser pour ce module.
    conclusion: CONCLUSION_PAR_DEFAUT,
    questions: [
      { slug: 'fete_solitaire', type: 'text', texte: 'Êtes-vous plutôt fête de famille ou loup solitaire ?', texte_en: 'Are you more of a family-gathering person or a lone wolf?' },
      { slug: 'apprecie_famille', type: 'text', texte: 'Qu\'est-ce que vous appréciez le plus dans votre famille ?', texte_en: 'What do you appreciate most about your family?' },
      { slug: 'agace_famille', type: 'text', texte: 'Qu\'est-ce qui vous agace, dans votre famille ?', texte_en: 'What annoys you about your family?' },
      { slug: 'valeurs_recues', type: 'text', texte: 'Quelles sont les plus belles valeurs que vous avez reçues ?', texte_en: 'What are the most valuable things your family passed down to you?' },
      { slug: 'qualites_heritees', type: 'text', texte: 'Quelles qualités avez-vous héritées de votre père ? De votre mère ?', texte_en: 'What qualities did you inherit from your father? From your mother?' },
      { slug: 'defauts_herites', type: 'text', texte: 'Quels défauts avez-vous hérités de votre père ? De votre mère ?', texte_en: 'What flaws did you inherit from your father? From your mother?' },
      { slug: 'education_recue', type: 'text', texte: "Comment décririez-vous l'éducation que vous avez reçue ? (Stricte, tolérante, communicante, à l'écoute, affectueuse, exigeante, autoritaire, protectrice, distante, joyeuse, permissive, punitive, austère, conflictuelle, festive, sereine, sportive, excessive...)", texte_en: 'How would you describe the upbringing you received? (Strict, tolerant, open, attentive, affectionate, demanding, authoritarian, protective, distant, joyful, permissive, punitive, austere, conflict-prone, festive, calm, athletic, excessive...)' },
      { slug: 'veut_enfants', type: 'text', texte: 'Voulez-vous avoir des enfants ? Depuis combien de temps avez-vous cette certitude ? Avez-vous déjà eu des doutes ? Lesquels ?', texte_en: 'Do you want to have children? How long have you been certain about this? Have you ever had doubts? What were they?' },
      { slug: 'combien_enfants', type: 'text', texte: 'Si oui, combien ? Et dans quel délai idéalement ? Y a-t-il un événement ou une situation qui vous semble être le bon moment ?', texte_en: 'If so, how many? And within what timeframe, ideally? Is there an event or situation that would feel like the right moment?' },
      { slug: 'pas_enfants', type: 'text', texte: "Si non, ou si vous n'êtes pas sûr·e, qu'est-ce qui vous retient ? Est-ce une position définitive ou encore ouverte ?", texte_en: "If not, or if you're not sure, what's holding you back? Is this a final position, or still open?" },
      { slug: 'education_donnee', type: 'text', texte: "Comment imaginez-vous l'éducation que vous donnerez à vos enfants ? (Adjectifs de la section « éducation reçue », ou vos propres mots.)", texte_en: 'How do you picture the upbringing you will give your children? (Use the adjectives from the "upbringing received" section, or your own words.)' },
      { slug: 'garde_enfants', type: 'text', texte: "Qui s'occupe des enfants au quotidien ? (Garde partagée, rôle de chacun·e, place du travail, aide extérieure.)", texte_en: "Who takes care of the children day to day? (Shared custody, each parent's role, the place of work, outside help.)" },
      { slug: 'desaccords_education', type: 'text', texte: "Y a-t-il des sujets sur lesquels vous sentez déjà que vous ne serez pas d'accord ? (Religion, école publique ou privée, écrans, discipline, alimentation.)", texte_en: 'Are there topics where you can already sense you will disagree? (Religion, public or private school, screen time, discipline, diet.)' },
      { slug: 'religion', type: 'text', texte: "Avez-vous une religion ou une pratique spirituelle ? (Pratiquant·e, croyant·e non pratiquant·e, agnostique, athée, autre.)", texte_en: 'Do you have a religion or a spiritual practice? (Practicing, believer but non-practicing, agnostic, atheist, other.)' },
      { slug: 'place_religion', type: 'text', texte: 'Quelle place tient la religion dans votre vie au quotidien ? (Fêtes religieuses, alimentation, prière, rites de passage.)', texte_en: 'What role does religion play in your everyday life? (Religious holidays, diet, prayer, rites of passage.)' },
      { slug: 'religion_origine', type: 'text', texte: "Et dans votre famille d'origine, quelle place tenait-elle ? Qu'avez-vous envie de conserver ? De laisser de côté ?", texte_en: 'And in the family you grew up in, what role did it play? What do you want to keep? What do you want to leave behind?' },
      { slug: 'transmission_religieuse', type: 'text', texte: 'Comment envisagez-vous la transmission religieuse aux enfants ? (Éducation religieuse, aucune, les laisser choisir.)', texte_en: 'How do you envision passing on religion to your children? (Religious education, none, letting them choose.)' },
      { slug: 'rituels_spirituels', type: 'text', texte: 'Y a-t-il des rituels religieux ou spirituels qui vous tiennent à cœur pour le couple ? (Cérémonie, bénédiction, fêtes, jeûne.)', texte_en: 'Are there any religious or spiritual rituals that matter to you as a couple? (Ceremony, blessing, holidays, fasting.)' },
      { slug: 'ou_vivre', type: 'text', texte: 'Où aimeriez-vous vivre, idéalement ? (Ville, campagne, banlieue, étranger.) Pourquoi ?', texte_en: 'Where would you ideally like to live? (City, countryside, suburbs, abroad.) Why?' },
      { slug: 'relation_famille_origine', type: 'text', texte: 'Quelle est votre relation à la famille d\'origine ? La proximité géographique compte-t-elle pour vous ?', texte_en: 'What is your relationship like with the family you grew up in? Does geographic proximity matter to you?' },
      { slug: 'endroits_refuses', type: 'text', texte: 'Y a-t-il des endroits où vous refuseriez de vivre ?', texte_en: 'Are there places you would refuse to live?' },
      { slug: 'desaccord_place', type: 'text', texte: 'Si vos réponses ne coïncident pas, quelle place laissez-vous à ce désaccord ? (Négociable, rédhibitoire, pas encore réfléchi.)', texte_en: "If your answers don't match, how much room do you leave for this disagreement? (Negotiable, a dealbreaker, haven't thought about it yet.)" },
    ],
  },
  {
    slug: 'communication', n: 6,
    titre: 'Nos modes de communication', titre_en: 'How We Communicate',
    sousTitre: 'Se parler, vraiment', sousTitre_en: 'Really talking to each other',
    description: "Comment vous vous parlez, ce que vous taisez, ce qui vous ferait mieux vous comprendre.",
    description_en: 'How you talk to each other, what you leave unsaid, what would help you understand each other better.',
    emoji: '💬', free: false,
    // Questions de fin de module : à personnaliser pour ce module.
    conclusion: CONCLUSION_PAR_DEFAUT,
    questions: [
      { slug: 'raconter_journees', type: 'text', texte: 'Vous arrive-t-il de vous raconter vos journées ? De quoi parlez-vous ?', texte_en: 'Do you tell each other about your day? What do you talk about?' },
      { slug: 'emotions', type: 'text', texte: 'Parlez-vous des émotions ressenties (joie, tristesse, colère) ?', texte_en: 'Do you talk about the emotions you feel (joy, sadness, anger)?' },
      { slug: 'exprimer_besoins', type: 'text', texte: "Êtes-vous capable d'exprimer à l'autre vos besoins (compliments, gestes tendres, encouragements, aide) ?", texte_en: 'Are you able to express your needs to your partner (compliments, affectionate gestures, encouragement, help)?' },
      { slug: 'comment_quand', type: 'text', texte: 'Comment et quand le faites-vous ? (Phrases claires, plaintes, attentes non exprimées, disputes, bouderies...)', texte_en: 'How and when do you do this? (Clear statements, complaints, unspoken expectations, arguments, the silent treatment...)' },
      { slug: 'reaction_autre', type: 'text', texte: "Comment l'autre réagit-iel, selon vous ?", texte_en: 'In your opinion, how does your partner react?' },
      { slug: 'reaction_moi', type: 'text', texte: "Et vous, comment réagissez-vous quand l'autre s'exprime ?", texte_en: 'And you, how do you react when your partner opens up?' },
      { slug: 'sujets_tabous', type: 'text', texte: 'Avez-vous des sujets tabous entre vous ? Pourquoi ? Que se passerait-il si vous en parliez ?', texte_en: 'Are there topics that are off-limits between you? Why? What would happen if you talked about them?' },
      { slug: 'peur_jugement', type: 'text', texte: "Avez-vous peur du regard ou du jugement de l'autre ?", texte_en: "Are you afraid of your partner's judgment?" },
      { slug: 'conditions_ideales', type: 'text', texte: 'Quelles seraient les conditions idéales pour en parler ?', texte_en: 'What would the ideal conditions be to talk about it?' },
      { slug: 'angoisses', type: 'text', texte: "Avez-vous des angoisses que vous aimeriez voir disparaître ? En parler à l'autre serait-il un bon moyen de vous y aider ?", texte_en: 'Do you have anxieties you wish would go away? Would talking to your partner about them help?' },
      { slug: 'sexualite_besoins', type: 'text', texte: 'Arrivez-vous à aborder ensemble vos besoins et vos attentes sur les questions de sexualité ?', texte_en: 'Are you able to discuss your needs and expectations around sex together?' },
      { slug: 'bilan_communication', type: 'text', texte: 'Après cet inventaire, est-ce que vous communiquez bien ? Que pouvez-vous améliorer ?', texte_en: 'After this review, do you communicate well? What could you improve?' },
      { slug: 'code_signal', type: 'text', texte: "Quel code pourriez-vous inventer pour signaler « ce n'est pas le moment » ou « il faut qu'on parle » ?", texte_en: 'What signal could you come up with to say "now\'s not a good time" or "we need to talk"?' },
    ],
  },
  {
    slug: 'intimite', n: 7,
    titre: "L'intimité", titre_en: 'Intimacy',
    sousTitre: 'Tendresse et désir', sousTitre_en: 'Tenderness and desire',
    description: "Comment vous vous manifestez votre amour et votre désir — en privé comme en public.",
    description_en: 'How you show your love and desire to each other — in private and in public.',
    emoji: '🔥', free: false,
    // Questions de fin de module : à personnaliser pour ce module.
    conclusion: CONCLUSION_PAR_DEFAUT,
    questions: [
      { slug: 'sexualite_besoins_2', type: 'text', texte: 'Arrivez-vous à aborder ensemble vos besoins et vos attentes sur les questions de sexualité ?', texte_en: 'Are you able to discuss your needs and expectations around sex together?' },
      { slug: 'tendresse', type: 'text', texte: 'Exprimez-vous votre tendresse à l\'égard de l\'autre ? Quand et comment, en privé et en public ?', texte_en: 'Do you express affection toward each other? When and how, in private and in public?' },
      { slug: 'besoins_autre_intimite', type: 'text', texte: "Quels sont, selon vous, les besoins et attentes de l'autre à ce sujet, en privé et en public ?", texte_en: "In your opinion, what are your partner's needs and expectations on this, in private and in public?" },
      { slug: 'satisfait_attention', type: 'text', texte: "Êtes-vous satisfait·e des marques d'attention de l'autre à votre égard (privé / public) ?", texte_en: "Are you satisfied with the affection your partner shows you (in private / in public)?" },
      { slug: 'manifeste_amour', type: 'text', texte: "Comment manifestez-vous votre amour à l'autre ? Et l'autre, que fait-iel selon vous ?", texte_en: 'How do you show your love to your partner? And what do you think your partner does?' },
      { slug: 'marques_ignorees', type: 'text', texte: "Y a-t-il des marques d'affection de l'autre auxquelles vous n'aviez jamais porté attention ?", texte_en: 'Are there signs of affection from your partner that you had never noticed before?' },
    ],
  },
  {
    slug: 'conflits', n: 8,
    titre: 'Nos disputes', titre_en: 'Our Arguments',
    sousTitre: 'Désamorcer, grandir', sousTitre_en: 'Defusing conflict, growing together',
    description: 'Comment vous vous disputez, comment vous vous réconciliez, ce que vous pourriez encore améliorer.',
    description_en: 'How you argue, how you make up, and what you could still improve.',
    emoji: '⚡', free: false,
    // Questions de fin de module : à personnaliser pour ce module.
    conclusion: CONCLUSION_PAR_DEFAUT,
    questions: [
      { slug: 'sujet_dispute', type: 'text', texte: 'À propos de quoi vous disputez-vous ?', texte_en: 'What do you argue about?' },
      { slug: 'quand_dispute', type: 'text', texte: 'Quand cela se manifeste-t-il ?', texte_en: 'When does it tend to happen?' },
      { slug: 'comment_ca_se_passe', type: 'text', texte: 'Comment cela se passe-t-il la plupart du temps ? Comment le vivez-vous ?', texte_en: 'How does it usually go? How do you experience it?' },
      { slug: 'frequence_dispute', type: 'text', texte: 'Vous disputez-vous souvent ? Comment commencent, puis se terminent vos disputes ?', texte_en: 'Do you argue often? How do your arguments start, and how do they end?' },
      { slug: 'solutions_desaccord', type: 'text', texte: 'Comment trouvez-vous des solutions satisfaisantes à deux en cas de désaccord ?', texte_en: 'How do you find solutions together that satisfy you both when you disagree?' },
      { slug: 'initiative_reconciliation', type: 'text', texte: "Qui est à l'initiative de la réconciliation, en général ?", texte_en: 'Who usually makes the first move to make up?' },
      { slug: 'ameliorations', type: 'text', texte: 'Les disputes aboutissent-elles à des améliorations ?', texte_en: 'Do your arguments lead to improvements?' },
      { slug: 'pardon_reel', type: 'text', texte: 'Comment êtes-vous sûr·e·s que vous vous êtes vraiment pardonné·e·s ?', texte_en: 'How do you know you have truly forgiven each other?' },
      { slug: 'avoir_raison', type: 'text', texte: "L'un·e de vous deux cherche-t-iel toujours à avoir raison ?", texte_en: 'Does one of you always try to be right?' },
      { slug: 'monopolise_parole', type: 'text', texte: "L'un·e ou l'autre a-t-iel tendance à monopoliser la parole ?", texte_en: 'Does either of you tend to dominate the conversation?' },
      { slug: 'disputer_moins', type: 'text', texte: 'Aimeriez-vous vous disputer moins souvent ?', texte_en: 'Would you like to argue less often?' },
      { slug: 'exercice_colere', type: 'text', texte: "Exercice : à tour de rôle, qu'est-ce qui vous vient à l'esprit quand vous pensez à ce qui vous met en colère ?", texte_en: 'Exercise: taking turns, what comes to mind when you think about what makes you angry?' },
      { slug: 'exercice_reformulation', type: 'text', texte: "Exercice de reformulation : reprenez un reproche en vous mettant à la place de l'autre — qu'est-ce que ça change dans votre perception ?", texte_en: "Rephrasing exercise: take a grievance and put yourself in your partner's shoes — how does that change your perception?" },
      { slug: 'communication_harmonieuse', type: 'text', texte: "Avez-vous réussi à appliquer les règles de communication harmonieuse (écoute active, sourire, regard) pendant cet exercice ?", texte_en: 'Were you able to apply the rules of harmonious communication (active listening, smiling, eye contact) during this exercise?' },
      { slug: 'bilan_dispute', type: 'text', texte: 'Bilan après une dispute : qu\'avez-vous compris ? À quoi vous engagez-vous désormais ?', texte_en: 'Reflecting after an argument: what did you understand? What do you now commit to?' },
    ],
  },
  {
    slug: 'engagement', n: 9,
    titre: 'Notre pacte de couple', titre_en: "Our Couple's Pact",
    sousTitre: 'Vœux et engagements', sousTitre_en: 'Vows and commitments',
    description: "L'aboutissement : ce à quoi vous vous engagez, ce que représente pour vous le mariage, vos vœux. Ce module se conclut par la rédaction de votre CDD de couple, le contrat qui formalise vos engagements mutuels.",
    description_en: "The culmination: what you commit to, what marriage means to you, your vows. This module ends with writing your Couple's Pact — the contract that formalizes your mutual commitments.",
    emoji: '📜', free: false,
    // Questions de fin de module : à personnaliser pour ce module.
    conclusion: CONCLUSION_PAR_DEFAUT,
    questions: [
      { slug: 'important_couple', type: 'text', texte: "Qu'est-ce qui est important pour vous et pour votre couple ? À quoi vous engagez-vous ? À quoi renoncez-vous ?", texte_en: 'What matters to you and to your relationship? What do you commit to? What do you give up?' },
      { slug: 'regles_quotidien', type: 'text', texte: "D'après toutes ces questions, quelles sont vos règles de couple au quotidien ? (Indispensable / souhaitable / négociable / inacceptable.)", texte_en: 'Based on everything you\'ve discussed, what are your everyday rules as a couple? (Essential / desirable / negotiable / unacceptable.)' },
      { slug: 'vivre_engagement', type: 'text', texte: "Comment vivez-vous l'engagement ?", texte_en: 'How do you experience commitment?' },
      { slug: 'qui_voulait_marier', type: 'text', texte: 'Qui a voulu / voudrait se marier en premier ? Pour quelles raisons ?', texte_en: 'Who wanted to / would want to get married first? For what reasons?' },
      { slug: 'mariage_changer', type: 'text', texte: 'Que pensez-vous que le mariage va changer pour votre couple ?', texte_en: 'What do you think marriage will change for your relationship?' },
      { slug: 'peurs_mariage', type: 'text', texte: 'Quelles peurs éventuelles pensez-vous vaincre avec le mariage ?', texte_en: 'What fears, if any, do you think marriage will help you overcome?' },
      { slug: 'sens_engager', type: 'text', texte: "Que veut dire pour vous « s'engager » ?", texte_en: 'What does "committing" mean to you?' },
      { slug: 'plus_belle_preuve', type: 'text', texte: "Quelle est, selon vous, la plus belle preuve d'engagement ?", texte_en: 'In your opinion, what is the most beautiful proof of commitment?' },
      { slug: 'souhaits_avenir', type: 'text', texte: "Quels sont vos souhaits pour l'avenir ?", texte_en: 'What are your wishes for the future?' },
      { slug: 'decouvrir_voeux', type: 'text', texte: "De quelle manière souhaitez-vous découvrir les vœux de l'autre ? (Par la poste, en privé, ensemble la veille...)", texte_en: "How would you like to discover each other's vows? (By mail, in private, together the night before...)" },
    ],
  },
  {
    slug: 'renouvellement', n: 10,
    titre: 'Le bilan annuel de couple (BAC)', titre_en: 'The Annual Couple Check-In (ACC)',
    sousTitre: 'Le module qui fait durer', sousTitre_en: 'The module that makes it last',
    description: 'À refaire chaque année, à votre date anniversaire : ce qui a marché, ce qui a été dur, ce que vous voulez pour la suite.',
    description_en: 'To redo every year, on your anniversary: what worked, what was hard, and what you want next.',
    emoji: '🌱', free: false,
    // Questions de fin de module : à personnaliser pour ce module.
    conclusion: CONCLUSION_PAR_DEFAUT,
    questions: [
      { slug: 'points_positifs', type: 'text', texte: 'Quels sont les points positifs que vous pouvez noter concernant votre couple, sur l\'année écoulée ?', texte_en: 'What positives can you note about your relationship over the past year?' },
      { slug: 'moments_difficiles', type: 'text', texte: 'Quels moments ont été plus difficiles à vivre ?', texte_en: 'Which moments were harder to go through?' },
      { slug: 'changeriez', type: 'text', texte: 'Qu\'est-ce que vous changeriez ?', texte_en: 'What would you change?' },
      { slug: 'exprime_besoins_bac', type: 'text', texte: "Avez-vous pu exprimer vos besoins et attentes vis-à-vis de l'autre ?", texte_en: 'Were you able to express your needs and expectations to each other?' },
      { slug: 'ajustements', type: 'text', texte: "Quels ajustements vous engagez-vous à faire pour l'autre ? Et l'autre, à quoi s'engage-t-iel pour vous ?", texte_en: 'What adjustments do you commit to making for your partner? And what does your partner commit to for you?' },
      { slug: 'projet_en_cours', type: 'text', texte: 'Avez-vous un projet en cours ? Qui fait quoi, quelles sont les avancées et les échéances ?', texte_en: "Do you have a project underway? Who's doing what, what's the progress, and what are the deadlines?" },
      { slug: 'nouveaux_projets', type: 'text', texte: "Voulez-vous lancer de nouveaux projets pour l'année à venir ? Qui va faire quoi, à quelle échéance ?", texte_en: 'Do you want to start new projects for the coming year? Who will do what, and by when?' },
      { slug: 'fierte_annee', type: 'text', texte: "De quoi êtes-vous fier·e cette année ?", texte_en: 'What are you proud of this year?' },
      { slug: 'gratitude', type: 'text', texte: "À quel sujet éprouvez-vous de la gratitude envers l'autre ?", texte_en: 'What are you grateful to your partner for?' },
      { slug: 'voeux_annee', type: 'text', texte: 'Quels sont vos vœux pour votre couple, cette année ?', texte_en: 'What are your wishes for your relationship this year?' },
    ],
  },
]

export function getModuleBySlug(slug: string): ModuleInfo | undefined {
  return MODULES.find(m => m.slug === slug)
}
