import type { ModuleInfo } from '@/types'

export const MODULES: ModuleInfo[] = [
  {
    slug: 'toi', n: 1,
    titre: 'Toi et Moi',
    sousTitre: 'Se (re)découvrir',
    description: "On croit se connaître par cœur. Ce module révèle les angles morts, avec tendresse.",
    emoji: '👁️', free: true,
    questions: [
      { slug: 'bonheur_def', type: 'text', texte: 'Quelle est ta définition du bonheur ?' },
      { slug: 'prefere', type: 'text', texte: "Qu'est-ce que tu préfères chez l'autre ?" },
      { slug: 'apporte', type: 'text', texte: "Qu'est-ce que l'autre t'apporte dans la vie ?" },
      { slug: 'trois_mots_moi', type: 'text', texte: 'Si tu devais te décrire toi-même en 3 mots, lesquels choisirais-tu ?' },
      { slug: 'trois_mots_autre', type: 'text', texte: 'Si tu devais décrire ton/ta partenaire en 3 mots, lesquels choisirais-tu ?' },
      { slug: 'petit_plaisir', type: 'text', texte: 'Quel est ton petit plaisir du quotidien, celui que personne ne soupçonne ?' },
      { slug: 'echelle_bonheur', type: 'text', texte: 'Sur une échelle de 1 à 10, dirais-tu que tu es heureux·se en ce moment ? Pourquoi ?' },
      { slug: 'echelle_bonheur_autre', type: 'text', texte: "À ton avis, quel chiffre l'autre donnerait-il à son propre bonheur, là maintenant ?" },
      { slug: 'fait_rire', type: 'text', texte: "Qu'est-ce qui te fait le plus rire chez l'autre ?" },
      { slug: 'reves_enfant', type: 'text', texte: 'Quand tu avais 5, 10, 15 puis 20 ans, que rêvais-tu de faire dans la vie ?' },
      { slug: 'reve_enfant_autre', type: 'text', texte: "Penses-tu connaître le rêve d'enfant de l'autre ? Essaie de le deviner avant qu'iel ne réponde." },
      { slug: 'metier_reve', type: 'text', texte: "Si on t'offrait le métier de tes rêves, sans aucune contrainte, lequel serait-il ?" },
      { slug: 'metier_reve_autre', type: 'text', texte: 'Selon toi, quel serait le métier de rêve de l\'autre ?' },
      { slug: 'fierte', type: 'text', texte: 'De quoi es-tu le/la plus fier·e, dans ta vie ou en ce moment ?' },
      { slug: 'fierte_autre', type: 'text', texte: "Selon toi, qu'est-ce qui rend l'autre le/la plus fier·e de lui/elle-même ?" },
    ],
  },
  {
    slug: 'nous', n: 2,
    titre: 'Nous',
    sousTitre: 'Notre histoire',
    description: "On revient sur ce qu'on a construit : la rencontre, les moments forts, ce qui nous fait tenir.",
    emoji: '💑', free: false,
    questions: [
      { slug: 'rencontre', type: 'text', texte: 'Raconte ici votre rencontre. Quels sont les moments clefs ?' },
      { slug: 'moments_forts', type: 'text', texte: 'Quels sont les autres moments forts de votre couple ?' },
      { slug: 'craquer_moi', type: 'text', texte: "Qu'est-ce qui t'a fait craquer chez l'autre, la toute première fois ?" },
      { slug: 'craquer_autre', type: 'text', texte: "Selon toi, qu'est-ce qui a fait craquer l'autre, chez toi, au tout début ?" },
      { slug: 'plait_aujourdhui', type: 'text', texte: "Et qu'est-ce qui vous plaît, aujourd'hui ? (Ce n'est pas toujours la même chose.)" },
      { slug: 'plait_aujourdhui_autre', type: 'text', texte: "À ton avis, qu'est-ce qui plaît le plus à l'autre chez toi, aujourd'hui ?" },
      { slug: 'serieux', type: 'text', texte: 'Quel est le moment où tu as su que « c\'était du sérieux » ?' },
      { slug: 'meilleure_decision', type: 'text', texte: 'Quelle est la meilleure décision que vous ayez prise ensemble ?' },
      { slug: 'a_change', type: 'text', texte: "Qu'est-ce qui a le plus changé depuis le début de votre relation ?" },
      { slug: 'toujours_ensemble', type: 'text', texte: "Qu'est-ce qui fait que vous êtes toujours ensemble, selon toi ?" },
      { slug: 'film', type: 'text', texte: 'Si votre couple était un film, lequel serait-il ? Pourquoi ?' },
      { slug: 'futur', type: 'text', texte: 'Comment imaginez-vous votre couple dans 5 ans ? Et dans 20 ans ?' },
      { slug: 'plus_traits', type: 'text', texte: 'Qui est le ou la plus : sociale ? Têtue ? Créative ? Susceptible ?' },
      { slug: 'plus_traits_2', type: 'text', texte: 'Qui est le ou la plus : romantique ? Généreux·se ?' },
      { slug: 'motive', type: 'text', texte: "Qui motive l'autre ? Qui trouve des solutions ?" },
      { slug: 'revient_premier', type: 'text', texte: 'Qui revient en premier après un désaccord, une dispute ?' },
      { slug: 'surnom', type: 'text', texte: 'Quel est votre surnom de couple, celui que vous donnent vos amis ou votre famille ?' },
    ],
  },
  {
    slug: 'quotidien', n: 3,
    titre: 'Le quotidien',
    sousTitre: 'La vie commune',
    description: "La charge mentale, la répartition des tâches, les petits gestes : ce qui fait un quotidien qui tient.",
    emoji: '🏠', free: false,
    questions: [
      { slug: 'depuis_quand', type: 'text', texte: 'Depuis combien de temps vivez-vous ensemble ?' },
      { slug: 'repartition', type: 'text', texte: "Comment décrirais-tu la répartition actuelle des tâches ? (Courses, repas, comptes/suivi des dépenses, ménage, lessives, rangement, réparations et bricolage, entretien voiture, trajets enfants, animaux, administratif, organisation des vacances...)" },
      { slug: 'devine_repartition', type: 'text', texte: "Avant de regarder sa réponse : essaie de deviner comment l'autre a réparti ces mêmes tâches." },
      { slug: 'accord_repartition', type: 'text', texte: "Êtes-vous d'accord avec cette organisation ? Trouvez-vous que c'est équitablement réparti ?" },
      { slug: 'attentes_jamais_dites', type: 'text', texte: "Qu'attends-tu de l'autre sur ce sujet, que tu n'as peut-être jamais dit ?" },
      { slug: 'attentes_autre', type: 'text', texte: "Que penses-tu que l'autre attend de toi sur ce sujet ?" },
      { slug: 'geste_touche', type: 'text', texte: "Quel est le geste ou l'attention qui te touche le plus, au quotidien ?" },
      { slug: 'geste_touche_autre', type: 'text', texte: "Selon toi, quel geste touche le plus l'autre, au quotidien ?" },
      { slug: 'difficile', type: 'text', texte: "Qu'est-ce qui est le plus difficile pour toi, dans la vie commune ?" },
      { slug: 'changer', type: 'text', texte: 'Que voudriez-vous changer dans votre quotidien de couple ?' },
      { slug: 'activite_seul', type: 'text', texte: 'Quelle activité aimerais-tu faire plus souvent, seul·e ? Et en couple ?' },
      { slug: 'activite_autre', type: 'text', texte: "Selon toi, quelle activité l'autre aimerait-il/elle faire plus souvent ?" },
      { slug: 'temps_deux', type: 'text', texte: "Avez-vous suffisamment de temps ensemble en tête-à-tête ? À quelle fréquence voudriez-vous vous accorder des moments à deux, et des moments seul·e ?" },
      { slug: 'loisir_commun', type: 'text', texte: 'Avez-vous un loisir en commun ?' },
    ],
  },
  {
    slug: 'projets', n: 4,
    titre: 'Les projets',
    sousTitre: 'Argent, travail, avenir',
    description: "L'argent, le travail, les rêves à deux : des sujets qu'on esquive trop souvent, à poser sur la table.",
    emoji: '🎯', free: false,
    questions: [
      { slug: 'econome_depensier', type: 'text', texte: "Êtes-vous plutôt économe ou dépensier·ère ? Dans quels domaines surtout (loisirs, vêtements, nourriture, voyages) ?" },
      { slug: 'reves_enfant_projets', type: 'text', texte: 'Quand vous aviez 5, 10, 15 puis 20 ans, que rêviez-vous de faire dans la vie ?' },
      { slug: 'dettes', type: 'text', texte: "Avez-vous des dettes ou des engagements financiers importants ? (Crédit, prêt étudiant, soutien à un·e proche...)" },
      { slug: 'relation_argent', type: 'text', texte: "Quelle est votre relation émotionnelle à l'argent ? (Il vous rassure, vous angoisse, vous est indifférent.) D'où vient ce rapport ?" },
      { slug: 'qui_gagne_plus', type: 'text', texte: 'Qui gagne le plus, dans votre couple ?' },
      { slug: 'organisation_financiere', type: 'text', texte: "Comment envisagez-vous l'organisation financière à deux ? (Comptes séparés, compte commun, modèle mixte, contribution proportionnelle.)" },
      { slug: 'decisions_financieres', type: 'text', texte: 'Qui prend les décisions financières importantes, dans votre modèle idéal ?' },
      { slug: 'depenses_perso', type: 'text', texte: 'Y a-t-il des dépenses que vous considérez comme personnelles et non soumises à discussion ?' },
      { slug: 'ecart_revenus', type: 'text', texte: "Si l'un·e de vous deux gagne nettement plus que l'autre, comment l'envisagez-vous ? Et si l'un·e arrête temporairement de travailler (enfant, maladie, projet) ?" },
      { slug: 'representation_travail', type: 'text', texte: 'Que représente le travail dans votre vie ?' },
      { slug: 'mutation', type: 'text', texte: "Avez-vous déjà envisagé de suivre l'autre dans le cadre d'une mutation professionnelle ? Comment réagiriez-vous ?" },
      { slug: 'ne_pas_travailler', type: 'text', texte: 'Accepteriez-vous que l\'autre ne travaille pas ?' },
      { slug: 'projets_financiers', type: 'text', texte: "Avez-vous des projets financiers à moyen terme ? (Achat immobilier, épargne, voyages, création d'entreprise...)" },
      { slug: 'projets_couple', type: 'text', texte: 'Avez-vous des projets de couple ? (Sorties, découvertes, travaux, décoration, déménagement, achat, vacances...)' },
      { slug: 'reve_fou', type: 'text', texte: 'Avez-vous un rêve fou personnel ? Est-ce réalisable ? Comment / pourquoi ?' },
      { slug: 'maison_reve', type: 'text', texte: 'Imaginez la maison de vos rêves et décrivez-la (ville, style, couleurs, matériaux, atmosphère).' },
      { slug: 'projet_imaginable', type: 'text', texte: 'Quel projet de couple pourriez-vous imaginer ensemble ?' },
    ],
  },
  {
    slug: 'famille', n: 5,
    titre: 'La famille',
    sousTitre: "D'où l'on vient, ce qu'on transmet",
    description: "L'éducation reçue, les enfants, la religion, le lieu de vie : ce qui vient de nos familles et ce qu'on choisit d'en garder.",
    emoji: '🌳', free: false,
    questions: [
      { slug: 'fete_solitaire', type: 'text', texte: 'Êtes-vous plutôt fête de famille ou loup solitaire ?' },
      { slug: 'apprecie_famille', type: 'text', texte: 'Qu\'est-ce que vous appréciez le plus dans votre famille ?' },
      { slug: 'agace_famille', type: 'text', texte: 'Qu\'est-ce qui vous agace, dans votre famille ?' },
      { slug: 'valeurs_recues', type: 'text', texte: 'Quelles sont les plus belles valeurs que vous avez reçues ?' },
      { slug: 'qualites_heritees', type: 'text', texte: 'Quelles qualités avez-vous héritées de votre père ? De votre mère ?' },
      { slug: 'defauts_herites', type: 'text', texte: 'Quels défauts avez-vous hérités de votre père ? De votre mère ?' },
      { slug: 'education_recue', type: 'text', texte: "Comment décririez-vous l'éducation que vous avez reçue ? (Stricte, tolérante, communicante, à l'écoute, affectueuse, exigeante, autoritaire, protectrice, distante, joyeuse, permissive, punitive, austère, conflictuelle, festive, sereine, sportive, excessive...)" },
      { slug: 'veut_enfants', type: 'text', texte: 'Voulez-vous avoir des enfants ? Depuis combien de temps avez-vous cette certitude ? Avez-vous déjà eu des doutes ? Lesquels ?' },
      { slug: 'combien_enfants', type: 'text', texte: 'Si oui, combien ? Et dans quel délai idéalement ? Y a-t-il un événement ou une situation qui vous semble être le bon moment ?' },
      { slug: 'pas_enfants', type: 'text', texte: "Si non, ou si vous n'êtes pas sûr·e, qu'est-ce qui vous retient ? Est-ce une position définitive ou encore ouverte ?" },
      { slug: 'education_donnee', type: 'text', texte: "Comment imaginez-vous l'éducation que vous donnerez à vos enfants ? (Adjectifs de la section « éducation reçue », ou vos propres mots.)" },
      { slug: 'garde_enfants', type: 'text', texte: "Qui s'occupe des enfants au quotidien ? (Garde partagée, rôle de chacun·e, place du travail, aide extérieure.)" },
      { slug: 'desaccords_education', type: 'text', texte: "Y a-t-il des sujets sur lesquels vous sentez déjà que vous ne serez pas d'accord ? (Religion, école publique ou privée, écrans, discipline, alimentation.)" },
      { slug: 'religion', type: 'text', texte: "Avez-vous une religion ou une pratique spirituelle ? (Pratiquant·e, croyant·e non pratiquant·e, agnostique, athée, autre.)" },
      { slug: 'place_religion', type: 'text', texte: 'Quelle place tient la religion dans votre vie au quotidien ? (Fêtes religieuses, alimentation, prière, rites de passage.)' },
      { slug: 'religion_origine', type: 'text', texte: "Et dans votre famille d'origine, quelle place tenait-elle ? Qu'avez-vous envie de conserver ? De laisser de côté ?" },
      { slug: 'transmission_religieuse', type: 'text', texte: 'Comment envisagez-vous la transmission religieuse aux enfants ? (Éducation religieuse, aucune, les laisser choisir.)' },
      { slug: 'rituels_spirituels', type: 'text', texte: 'Y a-t-il des rituels religieux ou spirituels qui vous tiennent à cœur pour le couple ? (Cérémonie, bénédiction, fêtes, jeûne.)' },
      { slug: 'ou_vivre', type: 'text', texte: 'Où aimeriez-vous vivre, idéalement ? (Ville, campagne, banlieue, étranger.) Pourquoi ?' },
      { slug: 'relation_famille_origine', type: 'text', texte: 'Quelle est votre relation à la famille d\'origine ? La proximité géographique compte-t-elle pour vous ?' },
      { slug: 'endroits_refuses', type: 'text', texte: 'Y a-t-il des endroits où vous refuseriez de vivre ?' },
      { slug: 'desaccord_place', type: 'text', texte: 'Si vos réponses ne coïncident pas, quelle place laissez-vous à ce désaccord ? (Négociable, rédhibitoire, pas encore réfléchi.)' },
    ],
  },
  {
    slug: 'communication', n: 6,
    titre: 'Nos modes de communication',
    sousTitre: 'Se parler, vraiment',
    description: "Comment vous vous parlez, ce que vous taisez, ce qui vous ferait mieux vous comprendre.",
    emoji: '💬', free: false,
    questions: [
      { slug: 'raconter_journees', type: 'text', texte: 'Vous arrive-t-il de vous raconter vos journées ? De quoi parlez-vous ?' },
      { slug: 'emotions', type: 'text', texte: 'Parlez-vous des émotions ressenties (joie, tristesse, colère) ?' },
      { slug: 'exprimer_besoins', type: 'text', texte: "Êtes-vous capable d'exprimer à l'autre vos besoins (compliments, gestes tendres, encouragements, aide) ?" },
      { slug: 'comment_quand', type: 'text', texte: 'Comment et quand le faites-vous ? (Phrases claires, plaintes, attentes non exprimées, disputes, bouderies...)' },
      { slug: 'reaction_autre', type: 'text', texte: "Comment l'autre réagit-iel, selon vous ?" },
      { slug: 'reaction_moi', type: 'text', texte: "Et vous, comment réagissez-vous quand l'autre s'exprime ?" },
      { slug: 'sujets_tabous', type: 'text', texte: 'Avez-vous des sujets tabous entre vous ? Pourquoi ? Que se passerait-il si vous en parliez ?' },
      { slug: 'peur_jugement', type: 'text', texte: "Avez-vous peur du regard ou du jugement de l'autre ?" },
      { slug: 'conditions_ideales', type: 'text', texte: 'Quelles seraient les conditions idéales pour en parler ?' },
      { slug: 'angoisses', type: 'text', texte: "Avez-vous des angoisses que vous aimeriez voir disparaître ? En parler à l'autre serait-il un bon moyen de vous y aider ?" },
      { slug: 'sexualite_besoins', type: 'text', texte: 'Arrivez-vous à aborder ensemble vos besoins et vos attentes sur les questions de sexualité ?' },
      { slug: 'bilan_communication', type: 'text', texte: 'Après cet inventaire, est-ce que vous communiquez bien ? Que pouvez-vous améliorer ?' },
      { slug: 'code_signal', type: 'text', texte: "Quel code pourriez-vous inventer pour signaler « ce n'est pas le moment » ou « il faut qu'on parle » ?" },
    ],
  },
  {
    slug: 'intimite', n: 7,
    titre: "L'intimité",
    sousTitre: 'Tendresse et désir',
    description: "Comment vous vous manifestez votre amour et votre désir — en privé comme en public.",
    emoji: '🔥', free: false,
    questions: [
      { slug: 'sexualite_besoins_2', type: 'text', texte: 'Arrivez-vous à aborder ensemble vos besoins et vos attentes sur les questions de sexualité ?' },
      { slug: 'tendresse', type: 'text', texte: 'Exprimez-vous votre tendresse à l\'égard de l\'autre ? Quand et comment, en privé et en public ?' },
      { slug: 'besoins_autre_intimite', type: 'text', texte: "Quels sont, selon vous, les besoins et attentes de l'autre à ce sujet, en privé et en public ?" },
      { slug: 'satisfait_attention', type: 'text', texte: "Êtes-vous satisfait·e des marques d'attention de l'autre à votre égard (privé / public) ?" },
      { slug: 'manifeste_amour', type: 'text', texte: "Comment manifestez-vous votre amour à l'autre ? Et l'autre, que fait-iel selon vous ?" },
      { slug: 'marques_ignorees', type: 'text', texte: "Y a-t-il des marques d'affection de l'autre auxquelles vous n'aviez jamais porté attention ?" },
    ],
  },
  {
    slug: 'conflits', n: 8,
    titre: 'Nos disputes',
    sousTitre: 'Désamorcer, grandir',
    description: 'Comment vous vous disputez, comment vous vous réconciliez, ce que vous pourriez encore améliorer.',
    emoji: '⚡', free: false,
    questions: [
      { slug: 'sujet_dispute', type: 'text', texte: 'À propos de quoi vous disputez-vous ?' },
      { slug: 'quand_dispute', type: 'text', texte: 'Quand cela se manifeste-t-il ?' },
      { slug: 'comment_ca_se_passe', type: 'text', texte: 'Comment cela se passe-t-il la plupart du temps ? Comment le vivez-vous ?' },
      { slug: 'frequence_dispute', type: 'text', texte: 'Vous disputez-vous souvent ? Comment commencent, puis se terminent vos disputes ?' },
      { slug: 'solutions_desaccord', type: 'text', texte: 'Comment trouvez-vous des solutions satisfaisantes à deux en cas de désaccord ?' },
      { slug: 'initiative_reconciliation', type: 'text', texte: "Qui est à l'initiative de la réconciliation, en général ?" },
      { slug: 'ameliorations', type: 'text', texte: 'Les disputes aboutissent-elles à des améliorations ?' },
      { slug: 'pardon_reel', type: 'text', texte: 'Comment êtes-vous sûr·e·s que vous vous êtes vraiment pardonné·e·s ?' },
      { slug: 'avoir_raison', type: 'text', texte: "L'un·e de vous deux cherche-t-iel toujours à avoir raison ?" },
      { slug: 'monopolise_parole', type: 'text', texte: "L'un·e ou l'autre a-t-iel tendance à monopoliser la parole ?" },
      { slug: 'disputer_moins', type: 'text', texte: 'Aimeriez-vous vous disputer moins souvent ?' },
      { slug: 'exercice_colere', type: 'text', texte: "Exercice : à tour de rôle, qu'est-ce qui vous vient à l'esprit quand vous pensez à ce qui vous met en colère ?" },
      { slug: 'exercice_reformulation', type: 'text', texte: "Exercice de reformulation : reprenez un reproche en vous mettant à la place de l'autre — qu'est-ce que ça change dans votre perception ?" },
      { slug: 'communication_harmonieuse', type: 'text', texte: "Avez-vous réussi à appliquer les règles de communication harmonieuse (écoute active, sourire, regard) pendant cet exercice ?" },
      { slug: 'bilan_dispute', type: 'text', texte: 'Bilan après une dispute : qu\'avez-vous compris ? À quoi vous engagez-vous désormais ?' },
    ],
  },
  {
    slug: 'engagement', n: 9,
    titre: 'Notre pacte de couple',
    sousTitre: 'Vœux et engagements',
    description: "L'aboutissement : ce à quoi vous vous engagez, ce que représente pour vous le mariage, vos vœux. Ce module se conclut par la rédaction de votre CDD de couple, le contrat qui formalise vos engagements mutuels.",
    emoji: '📜', free: false,
    questions: [
      { slug: 'important_couple', type: 'text', texte: "Qu'est-ce qui est important pour vous et pour votre couple ? À quoi vous engagez-vous ? À quoi renoncez-vous ?" },
      { slug: 'regles_quotidien', type: 'text', texte: "D'après toutes ces questions, quelles sont vos règles de couple au quotidien ? (Indispensable / souhaitable / négociable / inacceptable.)" },
      { slug: 'vivre_engagement', type: 'text', texte: "Comment vivez-vous l'engagement ?" },
      { slug: 'qui_voulait_marier', type: 'text', texte: 'Qui a voulu / voudrait se marier en premier ? Pour quelles raisons ?' },
      { slug: 'mariage_changer', type: 'text', texte: 'Que pensez-vous que le mariage va changer pour votre couple ?' },
      { slug: 'peurs_mariage', type: 'text', texte: 'Quelles peurs éventuelles pensez-vous vaincre avec le mariage ?' },
      { slug: 'sens_engager', type: 'text', texte: "Que veut dire pour vous « s'engager » ?" },
      { slug: 'plus_belle_preuve', type: 'text', texte: "Quelle est, selon vous, la plus belle preuve d'engagement ?" },
      { slug: 'souhaits_avenir', type: 'text', texte: "Quels sont vos souhaits pour l'avenir ?" },
      { slug: 'decouvrir_voeux', type: 'text', texte: "De quelle manière souhaitez-vous découvrir les vœux de l'autre ? (Par la poste, en privé, ensemble la veille...)" },
    ],
  },
  {
    slug: 'renouvellement', n: 10,
    titre: 'Le bilan annuel de couple (BAC)',
    sousTitre: 'Le module qui fait durer',
    description: 'À refaire chaque année, à votre date anniversaire : ce qui a marché, ce qui a été dur, ce que vous voulez pour la suite.',
    emoji: '🌱', free: false,
    questions: [
      { slug: 'points_positifs', type: 'text', texte: 'Quels sont les points positifs que vous pouvez noter concernant votre couple, sur l\'année écoulée ?' },
      { slug: 'moments_difficiles', type: 'text', texte: 'Quels moments ont été plus difficiles à vivre ?' },
      { slug: 'changeriez', type: 'text', texte: 'Qu\'est-ce que vous changeriez ?' },
      { slug: 'exprime_besoins_bac', type: 'text', texte: "Avez-vous pu exprimer vos besoins et attentes vis-à-vis de l'autre ?" },
      { slug: 'ajustements', type: 'text', texte: "Quels ajustements vous engagez-vous à faire pour l'autre ? Et l'autre, à quoi s'engage-t-iel pour vous ?" },
      { slug: 'projet_en_cours', type: 'text', texte: 'Avez-vous un projet en cours ? Qui fait quoi, quelles sont les avancées et les échéances ?' },
      { slug: 'nouveaux_projets', type: 'text', texte: "Voulez-vous lancer de nouveaux projets pour l'année à venir ? Qui va faire quoi, à quelle échéance ?" },
      { slug: 'fierte_annee', type: 'text', texte: "De quoi êtes-vous fier·e cette année ?" },
      { slug: 'gratitude', type: 'text', texte: "À quel sujet éprouvez-vous de la gratitude envers l'autre ?" },
      { slug: 'voeux_annee', type: 'text', texte: 'Quels sont vos vœux pour votre couple, cette année ?' },
    ],
  },
]

export function getModuleBySlug(slug: string): ModuleInfo | undefined {
  return MODULES.find(m => m.slug === slug)
}
